### PR TITLE
prepare for release

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
As discussed in another PR: this contains a few style and docstring changes to make things slightly more consistent and clear (in my opinion). 

Additionally, a few more tests and a `What's new` entry.

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.8.2 (default, Feb 27 2020, 15:26:21)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 1.0.0+86.gb35b4a5, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2

###### Verification 
Have you
- [x] included docstrings that follow PEP 257?
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] added or updated existing tests to cover the changes?
- [x] updated the documentation?

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville do you know why our coverage seems to have dropped by about 10% on 2020-04-24 (see [here](https://codecov.io/gh/lmfit/lmfit-py)). Something must have gone wrong with a merge or something... I'd like to take a look at that before we release a version - hopefully I'll have time tomorrow...

**Comment by newville** [comment]
@reneeotten Thanks! this all looks good, so I'll merge this, but hold off on 1.0.1 to give some time to look at the coverage change. 

I definitely had some "git badness" with the PR #610 last week or so and can believe I messed something up.   The coverage drop looks related to whether the `ui` folder is included in the count.   
I don't know if that is actually related, though.

**Comment by reneeotten** [comment]
> I definitely had some "git badness" with the PR #610 last week or so and can believe I messed something up. The coverage drop looks related to whether the `ui` folder is included in the count. I don't know if that is actually related, though.

@newville I just compared `tests/*.py` at a point earlier in the commit history where I know the coverage was around 92% with the `tests/*.py` in `master` and the tests are the same (with a few minor changes in more recent commits). So the tests have not changed, but I think you're right that now the files in the `ui` folder are counted. 

We should either exclude those, or perhaps even better, just get rid of them... That code hasn't been touched for years and I doubt that anyone is using it, what do you think?

**Comment by newville** [comment]
@reneeotten Yeah, let's remove it. it's there in the record if anyone wants it and we are not actually supporting it or documenting it or anything.

**Comment by reneeotten** [comment]
> @reneeotten Yeah, let's remove it. it's there in the record if anyone wants it and we are not actually supporting it or documenting it or anything.

okay, will you do that before making a release (perhaps just adding a sentence to the release notes as well), or do you prefer me to do a PR?

**Comment by newville** [comment]
@reneeotten I think it's OK to just go ahead and make the changes in master.

**Comment by reneeotten** [comment]
@newville okay, that's done

**Comment by newville** [comment]
@reneeotten Thanks!  I think we just tag the current master as 1.0.1 then and push a release.  I'll plan on doing that later today.

**Pull request merged**
