### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates the documentation to use ```jupyter-sphinx``` to run the examples and automatically generate the output (see #544). In addition, I made some minor corrections and additions to the text here and there.

Building the documentation will now take 30-60 seconds as it's actually executing the code (mainly the ```emcee``` example takes some time to run). But I think it's worth it, since we will now always have the correct output / figures.

I think this should be ready but I do appreciate other looking over it (@newville can you please test whether it locally builds correctly for you?). I am sure there are more improvements possible, so feel free to consider this a starting point ;)

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.7.4 (default, Jul 11 2019, 08:51:12)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 0.9.13+83.ga4c0074, scipy: 1.3.0, numpy: 1.16.4, asteval: 0.9.14, uncertainties: 3.1.1, six: 1.12.0

###### Verification 
Have you
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  Awesome!   This worked for me.  

Would it be worth adding a `requirements-doc.txt` file listing the full set of requirements (including `emcee` and `corner`)?

**Comment by reneeotten** [comment]
> @reneeotten Awesome! This worked for me.
> 
> Would it be worth adding a `requirements-doc.txt` file listing the full set of requirements (including `emcee` and `corner`)?

Good point. I don't really like adding more ```requirements-*.txt``` files.... what about we add them to the ```requirements-dev.txt``` we already have? I think building the documentation could be consider part of the development, right...?

**Comment by newville** [comment]
@reneeotten  Yes - `requirements-dev.txt` makes sense.

**Comment by reneeotten** [comment]
okay, I think all the requirements are now listed

**Comment by newville** [comment]
@reneeotten Thanks!

**Pull request merged**
