### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by newville**
replace #505, addressing a few small, unrelated but probably not-controversial issues:

1. allow a model's independent variable to be an object, addressing #492. Here, lists or tuples are automatically converted to ndarrays, but other objects are not. (To be clear panda Series work without being converted). A test is added using a non-trivial object. Nothing is changed about checking for NaNs - I think we cannot detect if a users object contains or generates NaNs.

2. remove nose from tests completely, and switch to pytest, addressing #504.

3. make sure that ModelResult.eval() does not overwrite the userkws dict, addressing #499.

### CODE REVIEW

**Comment by reneeotten** [comment]
I am a bit confused.. why did you force-push to ```master```? That should ideally never happen... it looks like you now lost the last commit with the changes from PR #503 (compare with the master branch in my fork: https://github.com/reneeotten/lmfit-py/commits/master).

In this PR, the last commit is also a bit weird now - it contains changes with respect to emcee from the PR that was already merged (and the commit message is a bit weird since you're actually changing np.testing.assert_raises with pytest.raises). But that's besides the point; let's figure out how to get back to the correct state of the master branch and then just merge in whatever way you feel comfortable!

**Comment by newville** [comment]
@reneeotten Sorry, I don't understand - the master branch looks OK to me.  I guess that 476bffc is a merge of recent commits from master back into this branch.  Does that seem like a problem to you?

**Comment by reneeotten** [comment]
no, I don't think it is correct. The master branch has only 1805 commits; if you compare that with the master in my fork (see link above), it is missing the commit where you merged the PR to handle complex-values models that FaustinCarter contributed. I saw that you force-pushed to master yesterday, which I found weird and made me take a look - it seems to have this has resulted in losing this commit.

PRs should only have commits that contain changes with respect to master, that's what I don't understand here...

**Comment by newville** [comment]
@reneeotten Huh, OK that seems weird.  I thought I was forcing a push from master into small_fixes.  I'll try to revert that.   Maybe this is my lack of understanding, but I'm not sure the concern for clean commits and squashing is really working out here.

**Comment by reneeotten** [comment]
@newville okay, that seems to be back now. As I said earlier, just commit and merge whichever way you feel comfortable with. Re-writing history / force-pushing on ```master ``` should ideally never happen, so if that's a risk with rebasing PRs and such because you're not familiar with these options then let's not attempt that again. I still think we can request PR submitters to squash their commits themselves and write informative commit messages when submitting a PR or after it's finalized. They'll never have write access the the ```lmfit``` repository anyway (so none of this can happen for them) and you will only need to push the "merge" button when you're happy with it. Anyway, we're back in business so let's move on!

**Comment by newville** [comment]
@reneeotten OK, I'll merge this one and chalk it up to a learning experience.  I thought the automatic squash wasn't too bad, but I am perfectly willing to try to get cleaner PRs and to request that PRs get cleaned up before merging.

I'm also perfectly willing to have you oversee commits. ;).

**Pull request merged**
