### PR TITLE
add token to codecov config file

### PR DESCRIPTION
**Pull request by newville**
###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [ ] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville thanks for looking into this. Can you please revoke the token, generate a new one, and put it in the "[Encrypted secrets"](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) in the repository instead as described [here](https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/)?

**Comment by newville** [comment]
@reneeotten Is that necessary?  It looks like the codecov job did run with the token in place.

**Comment by reneeotten** [comment]
> @reneeotten Is that necessary? It looks like the codecov job did run with the token in place.

let me try if it works like this with the new uploader. The `bashuploader` never needed this for some reason so the fact that it worked in this PR doesn't mean all that much. 

It's just that typically one doesn't want to expose tokens to the public through CI systems or anywhere else online. That's why there is this "encrypted secrets" feature in GitHub where you upload the token and then the CI can use it without having it showing to the outside world.

**Comment by newville** [comment]
@reneeotten Well, I'm not sure there is anything of value at codecov ;).    Then again, codecov says the token is not needed for public repos from Azure Pipelines or GitHub Actions (or several others) so maybe the problem is something else or more subtle?

**Comment by reneeotten** [comment]
> @reneeotten Well, I'm not sure there is anything of value at codecov ;). Then again, codecov says the token is not needed for public repos from Azure Pipelines or GitHub Actions (or several others) so maybe the problem is something else or more subtle?

True, so let me see if using this token does fix the problem with the new uploader. If not, then the problem is certainly elsewhere and I'll need to investigate a bit more.

**Comment by reneeotten** [comment]
@newville with the token added the new codecov uploader works fine (see #738). I would prefer not to have the token exposed in our CI and store it with GitHub as described in the links above. I could probably add the token you added here myself if you want, or you could generate a new one instead. Just let me know what you prefer.

**Comment by newville** [comment]
@reneeotten sorry for being dense, but why don't we just go back to not including the unneeded token?  Codecov says it does not need a token.  

Anyway, security with a key needs something of value to protect.  I really don't know what the token is protecting.   But it has to be stored somewhere on github or in the repo.  Why do we care where that is?

I am sort of more inclined to delete the PR and the codecov account rather than keep messing around with regenerating keys for it or putting them in "the right place" in a public project.

**Comment by reneeotten** [comment]
> @reneeotten sorry for being dense, but why don't we just go back to not including the unneeded token? Codecov says it does not need a token.

@newville sometime in the not-so-far-future they'll retire the bash uploader, so we'll need to switch to the new one. I tried to do that following their instructions in the other PR and based on your comment there you were in favor of doing so. For some reason that doesn't work... even though the documentation states that a token shouldn't be necessary for certain CI providers, including Azure. I am not sure whether that statement still applies to the new uploader though, but will investigate that.

At any rate, the PR (#738) fails to upload files without having a token in place and it works when I include the change you made here. I will try and make sure, either by trial-and-error or just opening a ticket upstream, whether such token is actually needed or if I am doing something wrong.

> Anyway, security with a key needs something of value to protect. I really don't know what the token is protecting. But it (the key) has to be stored somewhere on github or in the repo. Why do we care where that is?

I was just reading the instructions in the link I mentioned above (likely the first Google hit) and there it says to add this to the "Encrypted secrets" section in the GitHub settings. I agree that it's probably not too crucial to do so, but on the other hand it will also not take you more than 5 minutes to do it. But again, I am fine with whatever option you prefer. I'll take another look if I can get it to work without a token at all and if not (or not within the time I have available for this) I'll just add this commit in my PR and call it a day.

> I am sort of more inclined to delete the PR and the codecov account rather than keep messing around with regenerating keys for it or putting them in "the right place" in a public project.

That's a counter-productive idea and not necessary. Thank you very much for getting the token and putting up this PR; no need to do anything more from your side, I will do a bit more research and go for the solution that seems best.

**Comment by newville** [comment]
@reneeotten I'm still very leery of using codecov at all.  It lends itself to the gamification of code development and is an easy way to mistakenly prioritizing "coverage" over actual code quality.   I'm viewing **all** of the "git / github helper utilities and automatic tools for formatting with skepticism.   We spend a lot of time on and with them -- quite possibly more than actually working on features or bug fixes.     

I will be polite and say that *in my view* relying on codecov is problematic.  My suspicion is that I am actually recognizing a common and pernicious problem. 

It simpply never matters if a PR makes the coverage score go up or down by 1%. It does matter if a PR for an added feature includes a test and if that test is right and useful.  Coverage cannot show that.  Automated scoring of coverage for every PR is just unreliable noise.
So, the token is there.  I don't know why it is needed.

**Pull request closed without merging**
