### PR TITLE
various small changes

### PR DESCRIPTION
**Pull request by reneeotten**
This PR contains the following small updates:
- remove the seemingly unnecessary *.bat files from the repository
- update the INSTALL and release notes
- specify a random.seed in the examples that are included in the documentation to get consistent results (and updates the output of examples accordingly)
- add support for all ```scipy.optimize.minimize``` solvers in ```scalar_minimize```, the newest solvers are only added if the scipy version is new enough (and associated documentation/test updates)
- update the docstring for least_squares

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville this test probably sometimes fails because of the random nature of ```basinhopping```; and for the lower scipy versions one cannot use the ```seed``` argument. If that test keeps on failing (intermittently) I think we can just remove the ```assert(out.residual <= ret.fun)``` statement - looking at it now again it seems a bit redundant anyways...

**Comment by newville** [comment]
@reneeotten This now looks very close to 0.9.10 final to me, perhaps at the end of the week.  Anything else need fixing or cleaning up for that?   Any reason to delay releasing as 0.9.10?

**Comment by newville** [comment]
@reneeotten  OK, I'll aim for Wednesday, but it might not be until Thursday.  

For the currently open issues, #169, #332, and #359 seem relevant.  I think  #23, #76, and #375 can be closed as "wont/cant fix" -- I'll do that now.  I'm OK with leaving some  #382 and #239 open just they case the inspire someone.  But they're old enough that they could be closed too.

**Comment by reneeotten** [comment]
@newville oh, perhaps two small things that I just noticed.... and might be worthwhile to fix:

1. is the code in ```lmfit/ui``` still being used for anything? If not, we should probably get rid of it; otherwise it needs some fixing as it still import the removed internal asteval version.
2. running the tests with ```pytest``` does generate figures with matplolib, which isn't very nice for testing (e.g., it fails when I try and enable the tests in macports).

Let me know what you think and I can try and take a look tomorrow.

**Pull request merged**
