### PR TITLE
[WIP] Add the brute force method.

### PR DESCRIPTION
**Pull request by reneeotten**
This PR is an initial attempt to add the scipy.brute() method, which was discussed in #55 and deemed to be worthwhile. I am interested in this as well and decided to give it a try... It certainly needs some more work, but before doing so I would like to get some feedback and/or suggestions to see if I am on the right track here.

The grid search part works as intended (see "compare-scipy_brute-vs-lmfit_brute.py" for the comparison of the results between scipy and lmfit on the example in the scipy.brute documentation). When there are only boundaries it uses a uniform number of grid points (Ns, default=20) for all variables; if a parameter has the attribute "grid_step", it will use this value as the step size.

I still need to add the 'finish' minimization using the values from the grid search as initial guesses, but am not completely sure what is the best way to do that. I tried to call self.minimize() after updating the parameters, but to be honest I have a hard time figuring out if this actually works properly, and, if so, how to combine the results of the grid search and final minimization into one MinimizerResult... Any suggestions would be much appreciated!

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Thanks very much for taking this on.  I think this will be a very valuable addition.   I also think that it is worth trying to improve the interface and output compared to scipy's `brute`.   That is, we have nothing to be backward compatible with, and can do whatever we want.   So, I have a few suggestions / questions (comments welcome!):

1.  We should think about whether "number of steps" or "step size" for each Parameter makes the most sense.  I think that, like you have, "step size" is more natural, as it is in the same units as the Parameter value, and might be interpreted/informed from expected uncertainty or feature size.

2.  I think we need a way to gracefully handle unspecified (aka infinite) bounds.  This sort of goes with the previous point.  That is, if someone specifies a step size but no bounds for a Parameter, it might make sense to default to 11 steps: `steps = np.linspace(-5*step_size, 5*step_size, 11)`?   If one bound (say, lower bound) is given, that might default to `np.linspace(minval, minval+10*step_size, 11)`. If both bounds are supplied as well as the step_size, it might be  `steps = np.arange(minval, maxval+step_size/2.0, step_size)`.  Those are suggestions....

3. I think that if the outputs of `brute` are well organized (see next), it doesn't need a `finish` step.  That is, we can already swap out minimization methods easily, so if the results of `brute` can easily be fed back into `minimize()` using methods of `leastsq`, `nelder`, or `differential_evolution`, then that allows plenty of flexibility.

4. The output of `minimize(...., method='brute')` should be a `MinimizerResult`, which is mostly a collection of attributes such a `params` that holds the best values found. But, just as @andyfaff added a flatchain for MC work, I would propose that the `MinimizerResult` output from `method='brute'` include a collection of some number (10, 20, 10*nvariables, 1% of all the evaluations?) of the "best sets of parameters", sorted by the fit score used (say chi-square or neg-likliehood).  I would think a list of namedtuples with (score, parameters) pairs would be suitable (and be future-proof), but suggestions welcome.   That would allow the user to have (and serialize/store) many sets of parameters to then try the finishing step on.  Basically, if you're going to use this method, you already believe the parameter space is not smooth, so the single best score on the uniform grid may not be the closest to the true minimum.   If you take 11 steps for 5 variables, that's 160,000 function evaluations . You don't want 1 set of parameters from that, you want the top 50 or maybe even top 1500 sets of parameters.

I don't think any of those suggestions would be that hard to do.  Of course comments and other ideas are most welcome.  

The code does have to work on versions earlier than Py3.5, so the Py3.5-only syntax would have to be changed.   I don't think we'll drop Py2.7 support for a couple of years.

Anyway, again: thanks very much -- I think this will be really useful!

**Comment by reneeotten** [comment]
thanks for your comments Matt! If you say that it doesn't really need a finish step, then we can just wrap around the scipy.optimize.brute method (and setting `finish=None`) - and reorganize their output into the `MinimizerResult`. I like your suggestions and will take a look at them and update the PR.

For my specific purpose I would still want to do grid search using `brute` and do a `leastsq` with the best results from the grid search as initial values. So something like:
`fitter = lmfit.Minimizer(func, params)`
`result = fitter.minimize(method='brute', finish='leastsq')`
I don't have a clear idea on how you would do that, except for implementing some sort of optional `finish` step in the `brute` function - can you comment on that?

**Comment by newville** [comment]
@reneeotten 

> 
> thanks for your comments Matt! If you say that it doesn't really need a finish step, then we can just wrap around the scipy.optimize.brute method (and setting finish=None) - and reorganize their output into the MinimizerResult. I like your suggestions and will take a look at them and update the PR.

Right, one would just need to define 'grid_step' (or perhaps that should be 'brute_step'?) attribute for each Parameter to be examined (if that attribute doesn't exist, don't include it in the search?) and perhaps a 'brute_nsteps' attribute (default to 5 or 11 or 21?) to specify how many steps to take if the bounds don't clarify that.  

The `Minimizer.brute` method can convert those to the inputs needed for `scipy.optimize.brute` with `full_output=True`, then organize the results into a `MinimizerResult`, including  converting the top `N` parameter values into a list  of the top candidate results, say a namedtuple with 'score' and 'params'  (a copy of the users Parameters with values set to the corresponding grid values).

> For my specific purpose I would still want to do grid search using brute and do a leastsq with the best results from the grid search as initial values. So something like:
> fitter = lmfit.Minimizer(func, params)
> result = fitter.minimize(method='brute', finish='leastsq')
> I don't have a clear idea on how you would do that, except for implementing some sort of optional finish step in the brute function - can you comment on that?
> 

Yes, I think that would be the normal approach.  Ideally, it would go something like this:
```python
params = Parameters()
# add Parameters, set bounds, brute_step, etc

fitter = lmfit.Minimizer(func, params)
brute_result = fitter.minimize(method='brute')

# finish with leastsq, starting with the best result found with method=`brute`
result = fitter.minimize(method='leastsq', params=brute_result.params)

# optionally try starting from each of the top 25 results found by method='brute', 
# assuming that the top results gets stored in order of score as '.candidates',
# a namedtuple with 'params'  entry hold the corresponding Parameters
for i in range(25):
     pars = brute_result.candidates[i].params
     trial = fitter.minimize(method='leastsq', params=pars)
     if trial.chisqr < result.chisqr:
         result = trial
```

Again, those are all suggestions.

**Comment by reneeotten** [comment]
@newville I have updated the code taking into account all your suggestions. 

Regarding handling of boundaries: I would personally be fine with just requiring finite bounds on varying parameters (if you want to do a grid search, it's not too much to ask for bounds). On the other hand, it doesn't hurt to be a bit more flexible - and I implemented four different scenarios. 

Please let me know what you think!

**Comment by newville** [comment]
@reneeotten  Thanks so much!   On a first reading, this looks really good.  I'll try it out, but I am inclined to accept, unless there is some problem.

Anyone have any thoughts on this?   Any reason to not accept?

**Comment by reneeotten** [comment]
great! I'll go through the code and documentation once more myself as well and hopefully we can wrap this up.

One thing I was thinking about, should we return the raw output from `scipy.optimize.brute` (i.e., `x0`, `fval`, `grid` and `Jout` as result.brute_<parameter> for completeness? Also, do you think there is a reason to have a 'keep' attribute or should we just return everything as .candidates (I am not sure how much overhead there is to do so for large grid)?

**Comment by newville** [comment]
@reneeotten  OK, I looked at this a little more closely, and have a few suggestions:

- `brute()` keyword arguments should be explicit, not parsed from `**kws`.  That is, use `params=None` so that a Parameters set can be explicitly given, and make `keep=50` and `Ns=20` explicitly part of the call signature.  

- The `args` argument is a little confusing.   The idea with lmfit is that one is expected to supply `fcn_args` and `fcn_kws` when creating the `Minimizer` for the particular objective function, and then have the different methods use those args/kws that were defined for the Minimizer instance.  
So, the `args` for `scipy.optimize.brute` should get applied inside `Minimizer_residual` from the `fcn_args` set at `Minimizer.__init__()`.

- yes on adding the outputs `grid`, and `Jout` as part of the `MinimizerResult`.

- I think (but not a rigid opinion) that `keep` is worth keeping, mostly so as to get the best several results (not just the best 1 result) as a Parameters object that is ready for polishing.  With `grid` and `Jout`, one can create Parameters for all gird points if that is desired.

- It would be nice to have a small example for the examples/ directory and for the docs.   Do you have something, or should we borrow one of the standard "hard" problems, perhaps from the NIST_StRD set?

If you're up for making those tweaks to the function arguments and storing the results, go for it.   If not, let me know.   Either way, I think this is basically ready to go.

As I look at this  (but not for this PR), it looks like `Minimizer` might be better of with a `apply_bounds_transformation` attribute to turn bounds transforms on/off, as several solver methods now want to shut this off/on and make sure it is correctly set for the instance during its run.

**Comment by reneeotten** [comment]
> brute() keyword arguments should be explicit, not parsed from **kws.

I am sorry, but I am afraid that I don't fully understand what you mean here. I suppose `params=None` should be added so that it becomes `def brute(self, params=None, **kws)`? What is the purpose of this, isn't is sufficient just to use `self.params` after one does `fitter = lmfit.Minimizer(func, params)`? Regarding the `keep=50` and `Ns=20`, do you mean that this should be explicitly given in the call to `scipy_brute()` or in `def brute()`? It's not clear to me then how a user would update these values by giving them as **kws either when initializing the `Minimzer class` or when calling the `minimize` method of that class. I looked through the code and manual, but the whole keyword business still confuses me a bit... For example is there a difference (priority?) in passing **kws to the Minimzer class or to the minimize function call - or is the result equivalent?
 
> The args argument is a little confusing. 

okay, I think I understand what you mean and, if so, then the `args` argument shouldn't be necessary here so I removed it. 

> yes on adding the outputs grid, and Jout as part of the MinimizerResult.

done.

> I think (but not a rigid opinion) that keep is worth keeping, mostly so as to get the best several results (not just the best 1 result) as a Parameters object that is ready for polishing. With grid and Jout, one can create Parameters for all gird points if that is desired.

Fine with me, I just changed the `keep` argument such that if it's set to `True` it will convert all the grid points to a Parameters object and stores it in `.candidates`. If a number is provided it will only keep the # best scoring ones.

> It would be nice to have a small example for the examples/ directory and for the docs. Do you have something, or should we borrow one of the standard "hard" problems, perhaps from the NIST_StRD set?

I will look and try to make an example based on one of the problems in the set you mentioned.

**Comment by newville** [comment]
@reneeotten 

Sorry for being unclear.  I meant that the signature for `Minimizer.brute` should be

```python
 def brute(self, params=None, Ns=20, keep=50, **kws):
```

so that the main (documented) keywords are explicit in the call signature, and things in `kws` is meant to be passed on (to `scipy.optimize.brute()` in this case).  

FWIW, the `params=None` is for consistency with the other solvers, and is convenient in that new or modified Parameters can be passed in for a single Minimizer instance.  

For example, one might want to do
```python
myfitter = Minimizer(myfunc, ....)
params = Parameters()
....
init_result = myfitter.brute(params=params)

best_result = init_result

for cand in init_result.candidates:
    result = myfitter.leastsq(params=cand.params)
    if result.chisqrt < best_result.chisqr:
         best_result = result
```
and that means that one needs to be able to pass `params` into the solver methods.

On other pieces:

I don't think it's necessary to discuss all the arguments of `scipy.optimize.brute` in the docstring.   It's OK to leave these but the fact that `lmfit.Minimizer.brute` wraps `scipy.optimize.brute` is kind of an implementation detail.

> Fine with me, I just changed the keep argument such that if it's set to True it will convert 
> all the grid points to a Parameters object and stores it in .candidates. If a number is 
> provided it will only keep the # best scoring ones.

OK.  Maybe `keep='all'` ?   Because, 1 == True, so saying `keep=1` would keep all candidates, not just 1.

**Comment by reneeotten** [comment]
@newville okay, hopefully these last two commits cover everything.

One more question though, right now there isn't really a need for `**kws` in `brute()` since there are only keywords left that we do not want the user to change. Do you want me to keep it here for consistency with other methods or should I remove it?

Let me know if this is what you meant; if not, please let me know or feel free to make the change yourself. If you're happy with the code, I will clean up the commit history a bit, add an example and push the branch again for your consideration to merge.

**Comment by newville** [comment]
@reneeotten Great -- thanks so much for doing this!  

Yeah, if **kws isn't being passed on to any other functions, it's probably better to remove it.

**Comment by reneeotten** [comment]
@newville I cleaned up the commit history, added an example and I think it should be good to go now. 

I guess before a next release we should update the documentation (i.e., `brute_step` in the Parameter(s) and `brute` in `Minimizer`). If you want me to do that, please feel free to remind me about it at that time or, if you'd prefer to add this to the documentation right now, point me where to do this.

If you, or anyone else, has other concerns please let me know and I'd be happy to take a look at it.

**Comment by newville** [comment]
@reneeotten it seems like this PR is really really close to done, but development and discussion paused. Is this ready to merge, or is there more that you think should be done before merging?

If we're all happy with code and docstrings, and it is down to updates to the RST doc files, we can merge and work on the docs separately.   That is, I would be in favor of merging.

**Comment by reneeotten** [comment]
@newville I think that I addressed all your comments and suggestions in the last commits. It would be good though that you or someone else with more knowledge about the lmfit code takes a look at it to make sure I didn't miss anything. I can take one more look at the code this week myself and if you tell me where/what to do in the docs, I should be able to do this as well. In that case you can merge everything at the same time.

One issue I have however, but this is not related to the code I added, is with unwanted changes for `brute_step`/`min`/`max` in the `set` function in `parameters.py`. I am not sure whether this is a feature or not and, if you want, I can open a separate issue for this. 
Consider the following code:
```
pars = lmfit.Parameters()
pars.add('a', value=10, brute_step=0.5, min=0, max=20)
```
this works as intended. 

However, if one now does: `pars['a'].set(value=15)`
it resets the bounds to [-inf:inf] and brute_step to None. As far as I can tell from the `set` function this is correct behavior, but from a user perspective I am not sure...

**Comment by newville** [comment]
@reneeotten 

If you're up for adding the docs for brute to `docs/fitting.rst`, even just using Sphinx's `automethod` directive (as for `emcee` and others), that would be great.

I wouldn't want that to slow this down too much, but a couple weeks is fine.

> One issue I have however, but this is not related to the code I added, is with unwanted changes for brute_step/min/max in the set function in parameters.py. I am not sure whether this is a feature or not and, if you want, I can open a separate issue for this.
>    Consider the following code:
>  
>    pars = lmfit.Parameters()
>    pars.add('a', value=10, brute_step=0.5, min=0, max=20)
>
>    this works as intended.
>
>    However, if one now does: pars['a'].set(value=15) it resets the bounds to [-inf:inf] and brute_step to None. As far as I can tell from the set function this is correct behavior, but from a user perspective I am not sure...

Oh, that is a problem.  Please raise as a separate Issue.  I think it's solvable.

**Comment by newville** [comment]
@reneeotten OK, it's been a couple more weeks ;).   As earlier, I'm in favor of merging, once the conflict with #391 is resolved.   Were you planning on updating the docs?  Please give a status update and/or expected time ranges.  Thanks!

**Comment by reneeotten** [comment]
@newville yes, I know... time flies ;) But, it's really almost done and I promise to finish it today or this weekend!

I went already through the code again and for me it all works as intended. I rebased with master to resolve the conflict after changing the "set" function (the conflict you're seeing on this branch is from change #389, and is not related to #391 since that PR has not been merged with master yet). I would suggest to first merge this PR after it's done; @a-stark can then rebase his PR with master, make the appropriate changes (e.g., the name change you suggested and fix the failing tests), and then you can merge that as well. Let me know what you think; if you think it's easier that I add the changes suggested in #391 to this branch, that's fine with me as well.

Back, to this PR: I updated some docstrings, added it to the documentation (and made some other small adjustments to the docs) and added/updated tests. The only thing left is to update the `example/lmfit_brute.py` to give some proper examples, including how the ranges will be determined. As I said I'll try to do that today or otherwise finish it in the weekend - I'll push the changes as soon as I am done. 

Thank you for your patience!

**Comment by newville** [comment]
@reneeotten  Great, thanks for getting back to this!  There's not really a rush, but I'd like to see it not stall.  I think we should try to get a 0.9.6 release soon, and I'd much prefer to include this addition.

As you say, it's now somewhat related to #391, and I agree with that the addition of `Parameter.user_data` (or similar) should happen after rebasing this PR.   I think we can do both of these changes for 0.9.6, and maybe aim for "end of February" for that release.

**Comment by reneeotten** [comment]
@newville here you go; I think it's all good to go now! The latest changes should be clear from the commit messages and/or a quick look at the code and are minor, but if there is anything unclear or you want me to change something - please let me know.

**Comment by newville** [comment]
@reneeotten Great!   I also see a lot of fixes to the docs - thanks for that too.     

I'm in favor merging, and then working toward 0.9..6 release by the end of February, which I think will mostly need more doc improvements.    

Any objections from anyone on merging this brute force addition, or to the goal of aiming for 0.9.6 in a few weeks?

**Comment by reneeotten** [comment]
@newville sounds good to me!

Unfortunately, my changes to the documentation are mostly small and cosmetic... I guess the doc improvements are somewhat related to the docstring/autodoc discussion? Is there consensus on what to use (for consistent formatting one could, for example, use something like https://github.com/myint/docformatter)? It is quite a bit of work (and to be fair not too much fun) to go through all of the docstrings... So ideally that should happen only once, after there is a consensus or -for that matter- you've made a decision.

Perhaps you could open an issue or something similar related to a 0.96 release and add the things that should be done beforehand (some issues could probably be taken care of or closed as well)?

**Comment by newville** [comment]
@reneeotten  Thanks, there was some discussion on docstring formatting conventions at #354.   I prefer the napoleon style myself.

Using autodoc uniformly would be very good, as the docstrings and rendered docs should be consistent.  I think the program doc should be more than a simple rendering of the docstrings, but  that any doc of the API should be build from the docstrings. 

The current docs and docstrings are not very consistent in this ideal (entirely my fault, as I started the docs not using autodoc) and definitely need attention.

**Pull request merged**
