### PR TITLE
a few fixes: typos, updates for changes to uncertainties/asteval

### LINKED ISSUE #962: Typo in create_uvars() method
#### First Time Issue Code

Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
A pretty simple bug, short and sharp.
The "create_uvars" method in parameter.py always returns ufloats with an SD of zero.
Lines 519 and 521 of parameter.py try to access the _stderr_ attribute of a fitted Parameter, but have been incorrectly entered as _sdterr_, see below:

        uvars = {}
        has_expr = False
        vnames, vbest, vindex = [], [], -1
        savevals = self.valuesdict()
        for par in self.values():
            has_expr = has_expr or par.expr is not None
            if par.vary:
                vindex += 1
                vnames.append(par.name)
                vbest.append(par.value)
                if getattr(par, 'sdterr', None) is None and covar is not None:
                    par.stderr = sqrt(covar[vindex, vindex])
            uvars[par.name] = ufloat(par.value, getattr(par, 'sdterr', 0.0))

###### A Minimal, Complete, and Verifiable example
N/A

###### Fit report:
Not applicable, all fitting functionality proceeds as normal.

###### Error message:
No errors are raised during execution because you can always default to zero: `getattr(par, 'sdterr', 0.0)`

###### Version information
I'm currently using lmfit version 1.3.2

###### Link(s)

N/A

### PR DESCRIPTION
**Pull request by newville**
This fixes #962  and addresses some recent changes from `uncertainties` and `asteval` that were causing test failures.

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:11:10) [Clang 16.0.6 ]

lmfit: 1.3.2.post1+g7b9837ed.d20240810, scipy: 1.14.0, numpy: 1.26.4, asteval: 1.0.2, uncertainties: 3.2.2.post7+gce16269

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [x] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  This is a kind of an odd collection of fixes for various problems that were causing test failures, from small changes in `uncertainties`, `asteval`, and `sphinx-gallery`.  But, it allows the tests to be passed.

I'll wait a few days and then plan to merge this.  If any changes are needed for this later, I think we can clean it up.

**Comment by reneeotten** [comment]
@newville thanks - I'll take a look before the end of the week.

**Comment by reneeotten** [comment]
there was another, similar typo in the `create_uvars` method ;) I am looking at the documentation a little bit now -  don't really like adding of the docstrings (I know it's required for `sphinx-gallery`) but they will also show up in our in-line code in the documentation which I am not a fan of...

**Comment by newville** [comment]
@reneeotten Thanks!   I'll push a fix with the other typo in create_uvars shortly. 

I agree that docs strings in the examples are not ideal.   I did not see a simple workaround other than "add docstrings".  


For reasons I did not fully understand -- no doubt other changes to `sphinx-gallery` - I could not get all the examples in the gallery nicely -- the `doc_*` ones worked fine. 

Would it be OK with you if I tried `examples/documentation' and `examples/other`?   

FWIW, I am fine with closing this PR and redoing these different changees more cleanly -- it became a bit of a mess...

**Comment by reneeotten** [comment]
Please don't push anything here; I have it all done. It was just a simple configuration change in  conf.py that resolves all the apparent issues.

**Comment by newville** [comment]
@reneeotten OK, great..  thanks!

**Comment by newville** [comment]
@reneeotten Great, Thanks!   Does that show the non-documentation examples for you?  I don't see those....

**Comment by reneeotten** [comment]
I'm pretty sure it does... did you do "make clean" first?

**Comment by newville** [comment]
@reneeotten Yep, I did do a make clean.   

I think you need to change `conf.py` to have
```
sphinx_gallery_conf = {'examples_dirs': '../examples/',...}
```

to get all the examples to render. 

...and restore the reference at line 186 of `faq.rst`.

**Comment by reneeotten** [comment]
let me check again but I am pretty sure it works. Please make sure you have all the latest versions if dependencies installed (if that’s indeed needed then I’ll update the requirements).

**Comment by reneeotten** [comment]
Yeah, it works fine here. I just pushed one additional commit that changes the docstring for the examples. Now it doesn't use the full filename that is often too long to show under the thumbnails.

**Comment by newville** [comment]
@reneeotten OK, thanks!  With updates to various packages (I think jupyter-sphinx might have been the problem with my envrionment), that works.  Looks great.

OK to merge?

**Pull request merged**
