### PR TITLE
Docs: fix errors in example notebooks

### LINKED ISSUE #347: Example notebooks errors
I noticed that the lmfit notebooks need some fixes to be executable.

I have made the fixes, should I make a PR with executed on unexecuted notebooks?

I think that unexecuted notebooks keep the repository cleaner (and smaller).

### PR DESCRIPTION
**Pull request by tritemio**
Fix errors (missing imports, py3 prints, etc.) and add title and one-line description to notebooks.

In this PR notebooks are unexecuted (no output).

Fix #347.

### CODE REVIEW

**Comment by tritemio** [comment]
Note that the big diff in one notebook is due to the (automatic) conversion to the new notebook format.

**Comment by tritemio** [comment]
Oddly, the lmfit-model notebook gives an error related to NaNs in the input data with lmfit from current master (ae7884bf387ec3d9d00e70ee0434cc55340aac42). But I haven't found any NaN...

**Comment by newville** [comment]
@tritemio  @andyfaff Thanks -- I was seeing some errors (or weird messages, anyway) with some of the emcee modules too.  I'll try to investigate, but may not get to it for a few days.

**Comment by andyfaff** [comment]
What were the errors with the emcee machinery / examples?

**Pull request merged**
