### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by newville**

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville I am not sure how to have the coverage runs automatically uploaded and/or reported. Some of the other things regarding `pre-commit`, and `building documentation` and the different phases I have figured out already. If you want you can take my file from [here](https://github.com/reneeotten/lmfit-py/blob/azure-pipelines/azure-pipelines.yml) and perhaps incorporate the two?

**Comment by newville** [comment]
@reneeotten yeah, I'm still trying to figure this all out.  I have not yet attempted "pre-commit", "doc building", or "matrix of scipy/numpy versions" either.   At this point, I'm counting "got a very basic pipeline working and passing tests" as a win!

Anyway, suggestions are most welcome!   It would be fine to try out Github Actions too - I have no preference.   For sure, "Azure" seems like a whole universe.

**Comment by reneeotten** [comment]
> @reneeotten yeah, I'm still trying to figure this all out. I have not yet attempted "pre-commit", "doc building", or "matrix of scipy/numpy versions" either. At this point, I'm counting "got a very basic pipeline working and passing tests" as a win!
> 
> Anyway, suggestions are most welcome! It would be fine to try out Github Actions too - I have no preference. For sure, "Azure" seems like a whole universe.

Take a look at the file I mentioned in the previous comment. That has the whole pipeline we want set-up already; there are just a few things failing (e.g., Python 3.9 with minimum dependencies) that did work on Travis. That has likely to do with something different in the build environments that I haven't figured out yet. Only other missing thing is doing the `coverage` stuff.

**Comment by newville** [comment]
@reneeotten Oh thanks, I missed that link earlier.  Will do....

**Comment by reneeotten** [comment]
> @reneeotten Oh thanks, I missed that link earlier. Will do....

made a few more small changes, should be pretty good now. I pushed to this PR, but didn't preserve your original commits.... sorry about that. Once we have figured out the remaining things, I'll associate your GitHub handle with the commit.

**Comment by newville** [comment]
@reneeotten great thanks - don't worry about commit history here.  I think we're just trying stuff...

**Comment by newville** [comment]
@reneeotten  it looks like maybe building Python 3-10 (or maybe configuring packages like scipy for it?) isn't ready yet on Azure.  Should we allow this to fail or remove the test?  I'd like to merge this for 1.0.2.

I'm working on another branch to try to workaround (and test) for the problem of "symmetrically-bounded parameter not changing") seen at #700 and discussed on the mailing list, and maybe clean up one of the tests.

**Comment by reneeotten** [comment]
> @reneeotten it looks like maybe building Python 3-10 (or maybe configuring packages like scipy for it?) isn't ready yet on Azure. Should we allow this to fail or remove the test? I'd like to merge this for 1.0.2.

I cannot figure out how to set it to `allow_failures` as one can do with Travis. That is something that needs to be figured out as well as doing the coverage stuff before we can retire Travis and switch over completely. However, this is not. needed for releasing a new version so I would be fine with leaving it as-is for now as well.

**Comment by newville** [comment]
@reneeotten I agree, I'll just merge this....

**Pull request merged**
