### PR TITLE
Add MinimizerResult

### PR DESCRIPTION
**Pull request by newville**
This is a fairly large PR, altering the Minimizer class so that:
 
1. The `params` passed in a `Minimizer.__init__()` are not changed.
2. The fit (either by the `minimize` function or the `Minimizer.minimize()`, `Minimize.leastsq()`, or `Minimize.scalar_minimizer` methods return a newly defined `MinimizerResult` object.  
3.  `MinimizerResult` contains fit information (status, messages), statistics (chi-square, aic, etc), and the `params` that were actually updated in the fit.   It's basically an empty container class that holds all the fit results. 

An important note is that in this scheme a new `params` -- a copy -- is made at the beginning of each fit. 

I believe this more or less addresses issues #174, #183, and begins to address #197.   However, this changes the API in many subtle ways.  Many tests, examples, and docs had to be changed.  For example, the interface for the calculation of confidence intervals had to be changed -- it now needs *both* a `Minimizer` object (to do subsequent fits) and a `MinimizerResult` (as a starting point for its calculations). 

All tests pass, though some needed tweaking.   The docs for this version are currently at http://cars9.uchicago.edu/software/python/lmfit_MinimizerResult/

I'm not sure this is perfect, but it does seem like an improvement to have `Minimizer` remain unchanged by a fit, and have all fit-dependent results in the returned value.   Since this is a fairly big change, and will definitely break some existing scripts (though the fixes are generally easy) this definitely needs a  boost in version number, and consensus on whether this is the right design.

This does not change the behavior of the `Model` class (and so, it is still stateless -- I toyed with this, but the PR is large enough as it is).   If we think this `MinimizerResult` is worth keeping, that seems like an important next topic to re-consider.   I don't have a strong opinion on whether `Model` should be changed, actually. 

This was a fairly long time in development, and I am in no rush to merge this without ample discussion.  So, if you have time, please read and try out the examples, and see if this is worth merging.

### CODE REVIEW

**Comment by newville** [comment]
Any comments on this PR?   I think it's an improvement, but it will definitely break existing scripts (easy to fix, but not pain-free).  I'd greatly prefer some feedback on this, but it's been a month without any comments, and I think that silence has to be interpreted as "no objections".   Unless there are concerns, I'll plan on merging this in two weeks (June 28).

**Comment by tacaswell** [comment]
I am :+1: on this in principle.  I skimmed the changes, but I don't know enough of the existing code base to have sensible comments on a short time scale.

**Comment by gbouvignies** [comment]
If the minimization gets interrupted, e.g. KeyboardInterrupt, will it be possible to obtain 'params' values at the current iteration? Right now, as 'params' gets continuously updated, it is pretty straightforward to get the information.

**Comment by newville** [comment]
@tacaswell Thanks! 

@gbouvignies Good question, and this probably needs documenting.  Right now a  `MinizerResult``  is created just prior to each fit (in ``prepare_fit()``), and held in ``self.result``, which is used as internal state during the fit.   At the end of a fit, this is the return value.  So this object (including ``result.params``) will hold the "active parameters", and are available after an interrupted fit.   Of course, this ``result`` is guaranteed to be over-written for each fit.

**Pull request merged**
