### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by reneeotten**
A PR with some housekeeping before a next release, mainly fixing issues reported by static code analysis and PEP8 compliance. For ease of review each commit addresses a specific issue.

A few more points for consideration:
1. would you be willing to bump the minimum required scipy version to 0.15? In that case, one could clean up the code regarding `differential_evolution` (i.e., direct use of `scipy.optimize.differential_evolution` and no need to wrap it for use with `scalar_minimize`).
2. to make sure that lmfit actually works as intended with the minimum required scipy / numpy version, the Travis CI should actually use these versions. Right now if you look at the tests, it installs scipy version 0.18.1 and numpy version 0.11 in the conda environment.
3. the function inspect.getargspec() in model.py line 174 is deprecated since Python 3.0 and is removed in version 3.6. The documentation suggests to use inspect.signature() instead, but this doesn't exist in Python 2. I guess it's not extremely urgent yet, but perhaps someone with more knowledge about this specific part of the code could take a look at it.

The last commit only addresses some simple docstring issues, mainly annotating the missing ones and trying to comply with PEP257. However, more work is certainly required here (i.e., make sure there is a oneline-summary and all parameters / return values are documented, ....). What would be the best plan of action?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  I don't disagree with any of these changes, but they is sort of a mix of different, unrelated changes here, including doc formatting and order-of-import changes.  I'm not opposed to merging, but I also think that small PRs for each one would have been better.

For your other points:  Each of these should be a separate issue.  Briefly:  1 (require scipy 0.15) No, 2. (test against various scipy/numpy versions) Yes, and 3 (replace inspect.getargspec() with inspect.signature()) we should use inspect.getfullargspec() with Python 3.*.

**Comment by reneeotten** [comment]
@newville thanks for your comments Matt and I apologize if I didn't follow the recommended strategy with PRs... 

I see your point that putting the docstring-business in the same PR is perhaps a bit too much, but in my mind all other points made sense as they're all instigated by running `pylint` on the code. I will drop the last commit for now and continue on that locally and open another PR once that is more completed. Is it okay to leave the rest in one PR, or do you prefer me to split them up in ~15 separate PRs - either way is fine with me, I just thought that it would be easier for you to have them combined. Just let me know what you prefer and I can do so now and will do so in the future.

I will open a separate issue/PR for the other points.

**Comment by newville** [comment]
@reneeotten Thanks, and sorry for delay.  

Just to be clear, I'm actually +1 for merging this, but do think the other points you raise should be separate issues.  

Is anyone against merging this?

**Comment by tritemio** [comment]
👍

**Comment by newville** [comment]
Thanks @reneeotten !

**Pull request merged**
