### PR TITLE
fix 'linear' mode for RectangleModel (lmfit#815)

### PR DESCRIPTION
**Pull request by arunpersaud**
#### Description

Fix the linear mode for RectangleModel. Also update the documentation and update the tests. (#815)

Tests:
  * Using numpy functions now allows lineshape.rectangle to handle single floats, so the tests needed to be updated
  * added tests for step and rectangle to make sure we get A/2 at mu1 (and mu2)

Docs:
  * update to reflect code and make brackets in LaTeX equations a bit nicer

###### Type of Changes
- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

Python: 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]

lmfit: 1.0.0.post473+g125c830.d20221024, scipy: 1.9.3, numpy: 1.23.4, asteval: 0.9.27, uncertainties: 3.1.7

###### Verification 
Have you

- [x] included docstrings that follow PEP 257?

- [x] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [x] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [x] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@arunpersaud Thanks - I think this is good. I would intend to merge in a couple of days unless there are any other concerns or comments.

**Comment by reneeotten** [comment]
@arunpersaud looks good to me, thanks! If you'd be willing to amend  your commit message and add "Closes: #815" as the last line of the body that would be great as it will close the Issue automatically when the PR gets merged (then please remove the reference to the issue from the commit summary).

**Comment by arunpersaud** [comment]
just updated the commit message.

**Comment by newville** [comment]
@reneeotten OK to (squash and) merge?

**Pull request merged**
