### PR TITLE
make sure update_constraints() is called

### PR DESCRIPTION
**Pull request by newville**
make sure update_constraints() is called in residual function before calling users objective function.

### CODE REVIEW

**Comment by andyfaff** [comment]
Before you merge this I think there may be another way of doing this, one that works for a Parameters instance in isolation.

In `Parameter._getval` there are a couple of places where `Parameter._val` is assigned. The relevant lines being:

    self._val = self._expr_eval(self._expr_ast)

and
    
    if self.min > -inf:
        self._val = max(self.min, self._val)
    if self.max < inf:
        self._val = min(self.max, self._val)

My suggestion is that these lines are changed to:

    self.value = self._expr_eval(self._expr_ast)

and

    if self.min > -inf:
        self.value = max(self.min, self._val)
    if self.max < inf:
        self.value = min(self.max, self._val)

(Actually wouldn't

    self.value = max(self.min, min(self._val, self.max))

be faster to use here). The reason being that assigning to self.value also updates the `Parameters._asteval.symtable`. So when the value of a dependent parameter is next retrieved it'll be updated.  The real test is more complicated chained expressions.  SImilar to the example I gave, but when:

    a.expr = `2 * b`
    b.expr = `2 * c`

and you then change `c`.

**Comment by andyfaff** [comment]
I agree with `update_constraints` being expensive. You would only want to call that once per iteration.

**Comment by andyfaff** [comment]
So I just repeated the test outlined in #265, and it still fails even if `update_constraints` is called beforehand.  I think that `update_constraints` still needs to be called in `__residual`, but that my suggestions are the only way to fix the problem.

**Comment by newville** [comment]
@andyfaff   OK, I think there are a lot of interrelated issues and PRs, and the level of confusion is quite high.   I can't tell whether your 2nd post amends or replaces the 1st.     Are you still recommending the suggestions in the first PR?

The 3rd post is about #265 is wrong.  I will respond there.

I still don't understand why tests that work in master are failing in #261, and the discussion of `Model.prefix` and `Model.copy()` can't really go forward unless it is mixed with that PR, or the whole thing is reworked.   I'd like to aim for a little more care and clarity and try to solve one problem at a time.

**Comment by newville** [comment]
@andyfaff  we can still think about whether we should be setting `.value`, but for now I just wanted to clean up the actual bug, so we can move on the bigger and better things (like #261 !)

**Comment by andyfaff** [comment]
So why hadn't the bug reared itself in the wild? Can a test be added for
that?

**Comment by newville** [comment]
@andyfaff I *believe* that the fact that the value of an expression-based parameter might be "stale" (say, evaluated with the previous iteration of its dependencies) is not significant as all the values actually converge.  I'm not 100% certain of this, and definitely seems better to me to explicitly update the constraints.   

Updating the asteval symbol table for each new parameter value seems fine, but it doesn't actually remove the need for `update_constraints()`, which takes care nested dependencies (or tries very hard to do so).

**Pull request merged**
