### PR TITLE
BLD: use PEP517/PEP518

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR implements the required changes to comply with PEP517/PEP518 for installing Python packages. We'll provide a shim `setup.py` for as long as Python allows us to build stuff with `python setup.py install`. This change allows us to remove a few files since things are now consolidated in `setup.cfg` and `pyproject.toml`.

See for details the commit messages.

###### Type of Changes
- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.10.1 (main, Dec 10 2021, 16:18:48) [Clang 11.0.3 (clang-1103.0.32.62)]

lmfit: 1.0.3.post21+gd678024, scipy: 1.7.3, numpy: 1.22.0, asteval: 0.9.25, uncertainties: 3.1.6

The tests fail on Azure Pipelines for a few Python versions on linux.... reverting back to NumPy v1.21.5 avoids those failures, but I guess we'll have to fix them at some point. I just haven't had time to look in detail so for now I can live with the few test failures we get. 

###### Verification 
Have you
- [ ] included docstrings that follow PEP 257?
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [ ] verified that existing tests pass locally? See above
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [ ] added or updated existing tests to cover the changes?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Thanks very much for taking that on that task!   I agree this is necessary, even as I admit to being slightly jaded about "yes, this latest change in how installation works is certainly better than the previous 3 or 4" ;).    

This looks complete to me, including nice and clear updates to the install doc.   I'd be happy to merge when you think this is ready.

For the numpy 1.22 failures: I saw and responded to reports about the removal of long-deprecated(-but-looks-at-those?) numpy functions at https://github.com/xraypy/xraylarch/issues/335

I should check whether `asteval` has a similar problem - it very well might, which could explain the errors here.   And, now that I have a clear template and no excuse other than "all that other stuff to do", I should probably migrate `asteval` to use `pyproject.toml` and `setup.cfg` too. ;).  OK, honestly,  that may not happen until next week...

**Comment by rayosborn** [comment]
Don't you need to add the setuptools_scm-generated `version.py` to .gitignore, or has that already been done?

**Comment by reneeotten** [comment]
> For the numpy 1.22 failures: I saw and responded to reports about the removal of long-deprecated(-but-looks-at-those?) numpy functions at [xraypy/xraylarch#335](https://github.com/xraypy/xraylarch/issues/335)

this doesn't seem to have anything to do with deprecated functions - we don't use any of those. The weird thing is also that I cannot reproduce it locally on my Mac, the test-suite passes for all Python versions. A cursory look at the installed packages also suggests the versions that are installed in the CI are all the same - so right now I don't know why I keep getting this failures on my fork...

Funnily enough, it all passes now here :)

**Comment by newville** [comment]
@rayosborn Thanks - we need all the eyes we can get!  @reneeotten Great!

**Comment by newville** [comment]
@reneeotten Thanks!

**Pull request merged**
