### PR TITLE
Fixes to building and testing

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR fixes a few things regarding building and testing `lmfit`:
1. `pre-commit` hooks: update to latest versions, in CI only install them not update
2. Azure pipelines: update NumPy/SciPy versions for development version, use `pytest` for tests so that the build actually fails when tests fails, upload test/coverage results to Azure pipelines
3. tests: fix failing test when pandas is unavailable, fixes for SciPy 1.7.0, remove use of `numpy.testing.dec`, clean-up since minimum required SciPy version is 1.3
4. building: remove conda-recipe directory, already hosted at: https://github.com/conda-forge/lmfit-feedstock
5. building: use `setuptools_scm` instead of `versioneer`. @newville inspired by your change in `asteval`; however, I think it's easier to write a `versions.py` file and use that instead of doing the magic with `importlib.metadata` or `pkg_resources` to get the version number (at least until Python supports that intrinsically).
6. examples: set `np.random.seed` in examples for slightly less randomness ; sometimes building of the documentation fails because a fit doesn't converge within the specified evaluations, hopefully this resolves that issue.

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Verification 
Have you
- [ ] included docstrings that follow PEP 257?
- [ ] referenced existing Issue and/or provided relevant link to mailing list?
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] added or updated existing tests to cover the changes?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten That all looks good to me.  Ready for merging?

I like your use of setuptools_scm better than the hack that happened with `asteval` -- which I did not catch due to my own poor checking of switching CI to github actions.     FWIW, I still find actions is still good, just originally botched it (and, ugh, conda -- I seem to always have more trouble with conda than it is worth).   For `asteval` it seems like "zero extra dependencies" is a reasonable expectation, but that's not true for `lmfit`.   Anyway, I think switching `asteval` to that

     use_scm_version={'write_to': 'lmfit/version.py'},

would be ideal.

Slightly related: what I decided to do for another project was to have both the scm_version string and a "release_version" string so that docs could always be built with the proper version number (in case docs lag code release, for example). That is especially important with setuptools_scm because with that, you release '1.0.3', and then further commits get tagged as '1.0.4.devXX....', where as with versioneer it was '1.0.3++++'.  Personally, I prefer the versioneer scheme (the branch is derived from '1.0.3' and '1.0.4' might not ever be released -- it might get reverted or become '1.1.0' or '2.0.0' -- it is not '1.0.4' until that is tagged.).   Anyway, having it standardized is more important, but it did sort of inspire me to then also want to be able to have 'last released version'.  I'm not sure we need that here, but maybe keep it in mind as a possibility.

**Comment by reneeotten** [comment]
@newville I'll take a look at what you mentioned for the versioning used in the documentation. Let's leave this PR open for a little to give me a bit of time to take care of that and others to possibly comment on this.

**Comment by reneeotten** [comment]
@newville you can specify how `setuptools_scm` does versioning - what you prefer (and I agree) is called `post-release`. So the entry in `setup.py` will look like this:
```
use_scm_version={
    'write_to': 'lmfit/version.py',
    'version_scheme': 'post-release'},
```

I have updated that in the commit

**Comment by reneeotten** [comment]
@newville any remaining issues or can this be merged?

**Comment by newville** [comment]
@reneeotten looks great to me.  Happy to merge or for you to do it.

**Pull request merged**
