### PR TITLE
Nan policy message

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
Several questions on the mailing list have come up recently regarding the message ```ValueError: The input contains nan values```. The "input" referred here to the input of the ```_nan_policy``` function, but that's admittedly not so relevant for users... In fact, often it seems that users interpret this as "my input data contains NaN values" and if that's not the case assume there is something wrong with ```lmfit```. Most often, the problem isn't in the input data but in the output of the objective/model function...

This PR improves the message that is emitted if a ```ValueError``` is raised by ```_nan_policy``` and includes a link to the FAQ where more explanation is given. 

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.7.4 (default, Aug 14 2019, 15:53:38)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 0.9.14rc1+14.g6478b7d.dirty, scipy: 1.3.1, numpy: 1.17.0, asteval: 0.9.15, uncertainties: 3.1.2, six: 1.12.0

###### Verification 
Have you
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [x] verified that existing tests pass locally?
- [x] squashed/minimized your commits and written descriptive commit messages?

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville that's certainly a good idea. I've added that, let me know what you think.

**Comment by reneeotten** [comment]
right, now it fails an example ```example_emcee_Model_interface.py``` where ```nan_policy``` is set to ```omit```, but now it throws an ValueError in ```Model._residual``` before the actual ```nan_policy``` is considered. So I guess we should only raise that ```ValueError``` if ```nan_policy='raise'```?

**Comment by newville** [comment]
@reneeotten  Yes, I think that would be fine.  If setting a`nan_policy!=raise`,  the user is at least somewhat implicated in "dealing with nans".

**Comment by reneeotten** [comment]
@newville okay, I think this should be done now. It could use some tests to make sure the ValuErrors are raised at the correct time and I'll look into that as well. If you're eager to make a release though, I don't think there is a need to wait for that - please feel free!

**Comment by reneeotten** [comment]
okay, that should be it

**Comment by newville** [comment]
@reneeotten Great! Let's merge this and push out  0.9.14!

**Pull request merged**
