### PR TITLE
reduce codecov failures

### PR DESCRIPTION
**Pull request by newville**
This tries to address #733, seeing if we can have `codecov` run and basically never fail.

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

None.

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [ ] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
yes, pre-commit does consider a trailing blank line to be a failure.  Old habits from days when lines in files that did not end with `\n` might be ignored die hard.   Sad to have my time wasted by such unnecessary formatting requirements.

@reneeotten, if you're willing to take over this project, I'd be happy to move on.  Intentionally ending this with a return.

**Comment by reneeotten** [comment]
> yes, pre-commit does consider a trailing blank line to be a failure. Old habits from days when lines in files that did not end with `\n` might be ignored die hard. Sad to have my time wasted by such unnecessary formatting requirements.

@newville it is sometime hard to judge (at least for me) if you're just being sarcastic or genuinely annoyed. But from this PR and the previous one it's clearly the latter... Back-in-the-days when I tried to clean-up some of the code and I suggested starting to use `pre-commit` with some widely accepted standard coding styles (in PR #533) you seemed to be in favor of it. If that has changed in recent times then let's figure out how to move forward in a way where we still do some checks on the code, but not too stringent, that is a good compromise for both of us. For example, right now I did set up Azure in such a way that it will not even continue if `pre-commit` is unhappy about something; that can easily be changed so that at least the rest of the test-suite will be run regardless so that one can judge if the the code change actually causes functional breakage or only doesn't follow the style completely. I am fine with not failing or even merging a PR when it's just about code style.

> @reneeotten, if you're willing to take over this project, I'd be happy to move on. Intentionally ending this with a return.

I enjoy contributing to and collaborating on the project, but I would much rather keep you "in charge" of your own project. It would be a real shame to loose all the "institutional knowledge" of the creator of the code! If any of my well-intended efforts to contribute here caused this I am very sorry. Why don't we have an open discussion instead on how to move forward in a way to would work for you?!

**Comment by newville** [comment]
@reneeotten I am not being sarcastic.  I'm not opposed to having good workflows and checks,  but the general emphasis on "code quality" and formatting is a worrisome development over the past few years has been bothering me for a while now.  The over-application of PEP8 was bad enough.  I cannot express my loathing for the concept and philosophy of Black strongly enough - its mere existence and the suggestion of using it is turning me away from open-source scientific python projects.  

For lmfit, battling the requirements on formatting is not a good use of my time.  Like here: if codecov works with a trailing blank, why are we calling that a failure?  Here it is not a theoretical or rhetorical question.  Really, why are we choosing to say that
cf93902200db28a3c4db551146d85a48bc79d744 failed?  Not a rhetorical question: We made that choice. Why?

This has a chilling effect on contributions.  Like, *from me*.

I would definitely want to remove the `emcee` method from `minimizer`, might be willing to figure out how to make that a separate post-fit module.  Then again "emcee in lmfit" seems to need a lot of maintenance and support, so maybe "drop then decide" is a viable approach.

I would be interested in adding a BSplineModel.

I would be interested in writing a GUI for lmfit -- I have GUIs that use lmfit to help users build/run/compare/save models, fitting to real data, adjusting Parameters, etc.  These could be morphed into a general-purpose tool.

But, honestly, with a full plate of other things to do and other communities to serve,  having to work in a way that also has to satisfy additional formatting rules is enough of a turn-off that I will focus attention elsewhere.   This was always an all-volunteer effort.

**Comment by reneeotten** [comment]
> For lmfit, battling the requirements on formatting is not a good use of my time. Like here: if codecov works with a trailing blank, why are we calling that a failure? Here it is not a theoretical or rhetorical question. Really, why are we choosing to say that [cf93902](https://github.com/lmfit/lmfit-py/commit/cf93902200db28a3c4db551146d85a48bc79d744) failed? Not a rhetorical question: We made that choice. Why?

sure, in this specific case there is not really a good reason, except for -indeed- we (well probably me who added it, but nobody objected) made that choice by adding the `end-of-file-fixer` commit hook. I can certainly understand your frustration about adding/fixing code, running the test locally, submitting a PR and then have the `pre-commit hooks` complain about formatting issues, that you *know* do not affect its functionality. That was what I tried to convey earlier: these things only work reasonably well if they're are used as intended, namely *before *you commit code (hence the name). In the majority of the cases it will be "fixed" automatically and once you commit these changes you don't have to think about it anymore. But, if the consensus is that we do not want to use `pre-commit hooks` in a local development environment hen there is indeed no point of having them in the CI.

> This has a chilling effect on contributions. Like, _from me_.

I am not sure if that is true in general, but if it's the case for you that is certainly a sufficient reason to change things. If you feel strongly about not wanting to use any of them (or only keep a subset of them), please do make that change (whichever way you want to go with this it will not bother me sufficiently to stop contributing). 

> I would definitely want to remove the `emcee` method from `minimizer`, might be willing to figure out how to make that a separate post-fit module. Then again "emcee in lmfit" seems to need a lot of maintenance and support, so maybe "drop then decide" is a viable approach.
> 
> I would be interested in adding a BSplineModel.
> 
> I would be interested in writing a GUI for lmfit -- I have GUIs that use lmfit to help users build/run/compare/save models, fitting to real data, adjusting Parameters, etc. These could be morphed into a general-purpose tool.

These sound all like very useful and interesting ideas that would greatly benefit from your expertise!

> But, honestly, with a full plate of other things to do and other communities to serve, having to work in a way that also has to satisfy additional formatting rules is enough of a turn-off that I will focus attention elsewhere. This was always an all-volunteer effort.

I understand this has been (and always will) be an all-volunteer effort, but that is true for any of us. Again, I am not trying to argue about any of this and I don't know how to state it more clearly: I am sure everyone would hate to see you turn away from `lmfit`, especially for something as trivial as code formatting "rules". So please do make the changes as you see fit and let's move on!

**Pull request closed without merging**
