### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by newville**
This addresses a few small, unrelated but probably not-controversial issues:
 
1.   allow a model's independent variable to be an object, addressing #492.   Here, lists or tuples are automatically converted to ndarrays, but other objects are not. (To be clear panda Series work without being converted).  A test is added using a non-trivial object.  Nothing is changed about checking for NaNs - I think we cannot detect if a users object contains or generates NaNs.

2. remove `nose` from tests completely, and switch to `pytest`, addressing #504.

3. make sure that `ModelResult.eval()` does not overwrite the `userkws` dict, addressing #499.

### CODE REVIEW

**Comment by reneeotten** [comment]
these all look like good changes. 

I don't think though it makes sense to have both ```pytest``` and ```nose``` as requirements for the testing (if so, both of them should be listed in ```setup.py```). To me it appears that after removing ```nose``` the tests were failing only when calling ```assert_raises``` from ```numpy```. I don't fully understand why for some Python versions and dependency combinations the tests fail or pass, but that's another story. 

I only looked quickly, but isn't it possible to replace the ```assert_raise``` with an equivalent in ```pytest``` (perhaps just [```pytest.raises```](https://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/pytest_raises.html#asserting-about-exceptions-with-pytest-raises))?

**Comment by newville** [comment]
@reneeotten  Yes, that is my understanding too.   I think that older versions of numpy used nose as only  "minimum versions" and "latest version of py3.4" failed.   

I tried your suggestion -- remove nose from travis.yml and replace `assert_raises` with `pytest.raises`.    Travis isn't done but it looks like it will work.

Next, I'm going to try to replace '3.7-dev' with '3.7' in the travis.yml.   

Can we drop testing of '3.4' soon?

**Comment by reneeotten** [comment]
You cannot install Python 3.7 in Travis (see [here)](https://docs.travis-ci.com/user/languages/python/#development-releases-support).  I've seen workarounds for this issue in Travis, but in my opinion it's not worth the trouble. we anyway don't use the Python version from Travis but install a Coda environment, so it really doesn't matter that the python version in Travis says ```3.7-dev```.

**Comment by newville** [comment]
@reneeotten  Do you prefer "squash separately",  "squash and merge", or just "merge the mess"?

**Comment by newville** [comment]
@reneeotten I'm OK with closing this and making 3 individual PRs.  That would make more sense, and now that I know what those changes are, it won't be hard to do over the next couple days.

**Comment by reneeotten** [comment]
@newville no need to close this PR and open new ones. Just go to your branch and do an interactive rebase.

``` git rebase -i HEAD~8```

this will open-up the history and you can change the order of commits by just moving the lines around and change ```pick``` to  ```drop```, ```squash```, or whatever you prefer (see the description). There are several ways of getting to the same, desired result in this case... one of them is to do as shown below:

```
pick aabf1f7 auto-convert independent var to array only if it is a list or tuple -- allow complex objects as independent vars
pick b1f12df ModelResult.eval() and .eval_components() should not permanently overwrite .userkws
fixup 5288f07 fix typo
pick 900095d convert tests to not rely on nose, using pytest instead where needed
fixup b59a45b numpy tests still require nose to be installed
pick 47275c7 replace numpy.testing.assert_raises with pytest.raises, remove nose dependency
fixup f4d77bc replace 3.7-dev with 3.7 for Travis
fixup 28c8f84 revert to testing with 3.7-dev
```
save the changes and it will update your commits accordingly. As a last step you'll have to force-push the changes to the PR branch.

**Comment by newville** [comment]
@reneeotten Thanks, will do!

**Pull request closed without merging**
