### PR TITLE
FIX: set function of Parameter class

### PR DESCRIPTION
**Pull request by reneeotten**
This PR fixes the set function of the Parameter class, which currently inadvertently affects the max/min/expr settings. Issue and solution discussed in #389.

### CODE REVIEW

**Comment by reneeotten** [comment]
sorry, this was too quick - I forgot to run the tests.... I'll take a look and update.

**Comment by newville** [comment]
@reneeotten  No problem on a PR that fails tests (I do this all the time).  And also:  CI to the rescue!  The failing test is 
```python
    # test #4: explicitly setting a param value WITH vary=True
    #          will set it to be variable
    gamval = 0.7777
    params['gamma'].set(value=gamval, vary=True)
    assert(params['gamma'].expr is None)
    assert(params['gamma'].vary)
```

which is there to remind us of good point:  If one does `param.set(value=XXX, vary=True)`,  `expr` should be set to `None`.    That is, if `vary` changes state to `True`, then `expr` should be set to `None`.   Conversely, if `expr` changes state to `not None`,  `vary' should go to `False`.

**Comment by andyfaff** [comment]
Normally a PR should add tests to check for the original bug and test for
future regressions. Could you add some tests for this issue?

**Comment by reneeotten** [comment]
I updated `test_params_set.py` to check for the issue (i.e., resetting the min/max values when changing the value) and and added a few more tests to make sure that only the attribute provide to the `set` function is changed. 

For now I have removed the conditional updating of the expression since that resulted in the failing tests. I see that the `expr` and `vary` setting should be correlated and that works in the original implementation. 

I am not sure whether it's completely correct though, but perhaps I don't understand it properly. Let's say you have the following:
```
import lmfit
params = lmfit.Parameters()
params.add('a', value=10, min=0, max=100, vary=True, expr=None)
params.add('b', expr='2.0*a') 
```
In this case, since parameter `b` depends on `a`, the initial value of `b` is set correctly to 20 and the minimum/maximum values for `b` are automatically 0 and 200 (but these are not propagated into the min/max parameter). I do understand that a user shouldn't change the value/min/max attributes for parameter b if you want to keep the expression, but... If one does `params['b'].set(min=0)` it will result now in `<Parameter 'b', value=20.0 (fixed), bounds=[0:inf]>`, which is fixed but has no `expr` anymore.

Would it make sense to:
1. set `vary=True` whenever `exp=None` and vice versa `vary=True` whenever `exp!=None`
2. only remove the expr when you pass `''` to the `set` function, as far as I can tell right now whenever you call the `set` function right now it will remove `expr`
2. propagate the min/max values for parameters with an expression (optional and just for completeness, for example when you use `pretty_print`)

I can take a look at how to do this, after I am sure that I understand the intended behavior. Thanks!

**Comment by newville** [comment]
@reneeotten

> I updated test_params_set.py to check for the issue (i.e., resetting the
> min/max values when changing the value) and and added a few more tests to
> make sure that only the attribute provide to the set function is changed.
>
> For now I have removed the conditional updating of the expression since
> that resulted in the failing tests. I see that the expr and vary setting
> should be correlated and that works in the original implementation.
>
> I am not sure whether it's completely correct though, but perhaps I don't
> understand it properly. Let's say you have the following:
>
> import lmfit
> params = lmfit.Parameters()
> params.add('a', value=10, min=0, max=100, vary=True, expr=None)
> params.add('b', expr='2.0*a')
>
> In this case, since parameter b depends on a, the initial value of b is
> set correctly to 20 and the minimum/maximum values for b are
> automatically 0 and 200 (but these are not propagated into the min/max
> parameter). I do understand that a user shouldn't change the value/min/max
> attributes for parameter b if you want to keep the expression, but... If
> one does params['b'].set(min=0) it will result now in <Parameter 'b',
> value=20.0 (fixed), bounds=[0:inf]>, which is fixed but has no expr
> anymore.
>

Yes, that should be fixed.   Setting `min` should not set `expr` to `None`.


> Would it make sense to:
>
>    1. set vary=True whenever exp=None and vice versa vary=True whenever
>    exp!=None
>
>
No, I think it should be:  set `expr=None` when `vary` is explicitly set to
`True`, and set `vary=False` when `expr` is explicitly set to `not None`.


>
>    1. only remove the expr when you pass '' to the set function, as far
>    as I can tell right now whenever you call the set function right now
>    it will remove expr
>
>
Yes, or if `vary=True`, I think.


>    1. propagate the min/max values for parameters with an expression
>    (optional and just for completeness, for example when you use
>    pretty_print)
>
>
Constraint expressions can have complicated "intrinsic boundaries", and I
would not want to try to capture those.  In your example

```python
params.add('a', value=10, min=0, max=100, vary=True)
params.add('b', expr='2.0*a')

```

It might be "obvious" that the bounds for `b` are [0:200], but even with

```python

params.add('a', value=10, min=0, max=100, vary=True)
params.add('b', value=10, min=-50, max=50, vary=True)
params.add('c', expr='sqrt(a*a + b*b)')

```

the bounds on 'c' may be obvious to you, but it would be a pain to
calculate automatically -- the minimum value does not occur at the minimum
values for 'a' and 'b'.   I think it's better to not try.

OTOH, if a parameter has both an expression and explicit bounds, show the
explicit bounds

**Comment by reneeotten** [comment]
okay, I think this now solves the issue and both for parameters with/without expression. It passes the previous tests as well as the ones I added in `test_params_set.py` to test for the correct behavior (as I understand it). I addition, I made a change to test_nose.py that previously was giving a DeprecationWarning, but now with fails on numpy 1.12.

As always, I'd appreciate feedback and since it's rather crucial that this is done correctly, please double-check for correctness ;)

**Comment by newville** [comment]
@reneeotten This looks very good to me.  It's definitely an improvement over the previous behavior, and passing all tests old and new.   And thanks for making explicit ints for the numpy deprecation warning. 

I'm +1 on merging.  Any objections?

**Comment by reneeotten** [comment]
@newville great! If everyone agrees, I can rebase with master and squash some of the commits to clean up the history a bit - just let me know.

As you probably noticed I removed the test for min/max equal to `None` and, if so, setting them to `inf` in the set function. After initializing the parameter, the values for `min/max` are anyway never `None` anymore even if you explicitly initialize them with `None`, since the `_init_bounds()` will take care of that. There might be a few more places to clean up redundant code like this a little, but I haven't really checked.

I do think that the behavior is now consistent with the description in the manual, but I can go through that part once I get around adding `brute` to the documentation - that's next on the to-do list.

**Comment by newville** [comment]
@reneeotten  I'm not that concerned about squashing commit histories; recording the process fine.  I certainly don't squash my PRs.   We allow ourselves to make mistakes but we try to learn from them. 

I think removing `if self.min is None: self.min = -np.inf` at the end of `Parameter.set()` is OK. The value for `self.min` should not be `None` here. 

There is a separate "potential issue" in that if someone explicitly sets min/max to `None`:
```python
x = Parameter('alpha', value=1, min=-10)
x.set(value=3)
x.max  = None
```
there can be a problem that the value will be stuck at the minimum value.   This is not a problem that `set()` can solve.  There *could* be an explicit test for min/max is `None` in `Parameter._getval()` or we could just say "don't do that".    I have no preference on that.

Anyway, I think this PR is fine as it is.

**Comment by newville** [comment]
Thanks @reneeotten !

**Pull request merged**
