### PR TITLE
almost ready to release 0.9.14?

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates the release notes and links to them in the documentation under the installation instructions. Additionally, new contributors were added to ```THANKS.txt```.

@newville I think with this we should be about ready to release a new version, or is there anything that I've missed?

###### Type of Changes
- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.7.4 (default, Aug 14 2019, 15:53:38)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 0.9.13, scipy: 1.3.1, numpy: 1.17.0, asteval: 0.9.14, uncertainties: 3.1.2, six: 1.12.0

###### Verification 
Have you
- [x] verified that existing tests pass locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  Yep, that looks good.  Will merge.  I've been breaking/fixing things with asteval over the past couple days, and will make a 1-liner PR here shortly.  If that passes, I will merge and tag 0.9.14rc1.

I've had some inconsistencies with the gallery generation, but I think that doesn't need to hold up the release of 0.9.14.

**Comment by reneeotten** [comment]
> I've had some inconsistencies with the gallery generation, but I think that doesn't need to hold up the release of 0.9.14.

that's a bit of vague description - can you elaborate on what inconsistencies, what are the (error) messages?

**Comment by newville** [comment]
@reneeotten  Yeah, sorry for the vagueness. The problems I was seeing were not always reproducible and different on Linux and Mac.   It seemed like it was sometimes due to `model_loadmodelresult`, but I'm not sure if "expected_failing_examples" was tripping me up (or really why that one is expected to fail, unless there's some oddities about how sphinx might load/run the examples in separate processes or something... ).

Anyway, on at least one linux box with Py37, it is working, at least mostly.  I get a couple of warnings of
```
writing output... [100%] whatsnew                                                                                                                                                                         
/home/newville/Codes/lmfit-py/doc/examples/index.rst:88: WARNING: undefined label: sphx_glr_examples_dl.py (if the link has no caption the label must precede a section header)
/home/newville/Codes/lmfit-py/doc/examples/sg_execution_times.rst:24: WARNING: undefined label: sphx_glr_examples_dl.py (if the link has no caption the label must precede a section header)
generating indices...  genindexdone
```

that I don't quite understand.  That `sphx_glr_examples_dl.py` seems somehow associated with 
`example_fit_with_inequality`.

I also get what looks like an error message from `sphinx_gallery` after the HTML is built:

```
The HTML pages are in _build/html.

Sphinx-gallery successfully executed 36 out of 36 files subselected by:                                                                                     

    gallery_conf["filename_pattern"] = '/documentation|/example_'                                                                                           
    gallery_conf["ignore_pattern"]   = '/doc_'                                                                                                              

after excluding 0 files that had previously been run (based on MD5).                                                                                        


Exception occurred:
  File "/home/newville/anaconda3/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 524, in summarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failing:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/newville/Codes/lmfit-py/examples/documentation/model_loadmodel.py
-------------------------------------------------------------------------------
The full traceback has been saved in /tmp/sphinx-err-4df72fm1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!


```


That traceback file has


```
# Sphinx version: 2.2.0
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   copying extra files...
#   done
#   dumping search index in English (code: en)...
#   done
#   dumping object inventory...
#   done
#   build succeeded, 3 warnings.
#   
#   The HTML pages are in _build/html.
#   Sphinx-gallery successfully executed 36 out of 36 files subselected by:

    gallery_conf["filename_pattern"] = '/documentation|/example_'
    gallery_conf["ignore_pattern"]   = '/doc_'

after excluding 0 files that had previously been run (based on MD5).
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/newville/anaconda3/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.extlinks (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.napoleon (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.todo (2.2.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx/ext/todo.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /home/newville/anaconda3/lib/python3.7/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   jupyter_sphinx.execute (0.2.1) from /home/newville/anaconda3/lib/python3.7/site-packages/jupyter_sphinx/execute.py
#   sphinx_gallery.gen_gallery (0.4.0) from /home/newville/anaconda3/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py
Traceback (most recent call last):
  File "/home/newville/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/newville/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 381, in build
    self.events.emit('build-finished', None)
  File "/home/newville/anaconda3/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/home/newville/anaconda3/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 524, in summarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Examples expected to fail, but not failing:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/newville/Codes/lmfit-py/examples/documentation/model_loadmodel.py
------------------------------------------------------------------------------


```

I *think* that error is benign, but I'm not 100% sure.  The gallery looks fine to me, though I do notice one odd `sphx_glr_examples_dl.py` which looks like it must have been automatically added.

**Comment by reneeotten** [comment]
that is confusing indeed - I get consistently the same results on my Mac as what happens on Travis...

The ```model_loadmodel.py``` always fails for me and this is caused by the ```sphinx_gallery/gen_gallery.py``` conversion script; I haven't been able to figure out why... As you can see in the ```doc/doc_examples_to_gallery.py``` files, I actually do execute the scripts that save a Model/ModelResult first and copy the .sav file to the proper directory. In that case, even if the "load" script is run before the "save", it will still have the correct ".sav" file present.

I do see ```WARNING: undefined label:``` messages sometimes, but that's always resolved by doing a ```make clean``` first, so please give that a try as well. 

Finally, can you please try do the exact same thing as on Travis and, create a fresh conda environment ```conda create -q -n test_env python=3.7 numpy scipy six pandas matplotlib dill sphinx jupyter_sphinx corner sphinx-gallery``` and try it again? If that doesn't give the same results as for me/Travis then I am really confused about it. If there are issues, we can carefully compare the versions of the packages involved and make sure we specify those explicitly.

**Comment by newville** [comment]
@reneeotten  Yeah the environment I was running in on MacOS was a complete mess.   When I install everything with an up-to-date conda environment and using `conda-forge` versions everything runs fine.  

I looked into the error with `model_loadmodel` a bit more.  I don't know for sure the whole story, but I think this is due to the way `sphinx-gallery` is running the code in an embedded `exec()`. 

I will try to make a PR with some small tweaks to `doc_examples_to_gallery.py` and `doc/Makefile` soon....

**Pull request merged**
