### PR TITLE
fix issue about lognormal center

### LINKED ISSUE #644: hint is wrong for lognormal model
#### Description
Lognormal model in lmfit use this formula for fitting:
```latex
f(x; A, \mu, \sigma) = \frac{A}{\sigma\sqrt{2\pi}}\frac{e^{-(\ln(x) - \mu)^2/ 2\sigma^2}}{x}
```
I use this model to fit my data but i failed several times to use this model. 

I found that \mu is limited to be positive but \mu should not be limited in math. I think some one is confused with another representation of lognormal function:
```latex
f(x; A, \mu, \sigma) = \frac{A}{\sigma\sqrt{2\pi}}\frac{e^{-(\ln(x) - \ln(\mu))^2/ 2\sigma^2}}{x}
```
where a \ln is applied to \mu and \mu should be limited to be greater than 0.

I set the limit of \mu manually and it works.

I prefer to changing the model to \ln one to fix the bug.

###### Version information
Python: 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0]

lmfit: 1.0.1, scipy: 1.3.3, numpy: 1.17.4, asteval: 0.9.18, uncertainties: 3.0.3

### PR DESCRIPTION
**Pull request by YoshieraHuang**
#### Description
fix #644 

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

### CODE REVIEW

**Comment by reneeotten** [comment]
thank you very much @YoshieraHuang for the issue report and the PR! In the future, please do provide all the information in the PR template. 

One of the tests is currently failing, I don't know yet why (but you would have noticed this when running the tests locally as requested in the PR template), but that will need to be fixed before the PR can be merged. Additionally, please update your commit message to something more descriptive than `Update models.py`. I would think something along the lines `FIX: center in lognormal model can be negative`.

**Comment by YoshieraHuang** [comment]
> thank you very much @YoshieraHuang for the issue report and the PR! In the future, please do provide all the information in the PR template.
> 
> One of the tests is currently failing, I don't know yet why (but you would have noticed this when running the tests locally as requested in the PR template), but that will need to be fixed before the PR can be merged. Additionally, please update your commit message to something more descriptive than `Update models.py`. I would think something along the lines `FIX: center in lognormal model can be negative`.

How can I modify a commit message online on github? And i cannot revert the PR template. Should I close this and issue a new PR?

**Comment by YoshieraHuang** [comment]
> thank you very much @YoshieraHuang for the issue report and the PR! In the future, please do provide all the information in the PR template.
> 
> One of the tests is currently failing, I don't know yet why (but you would have noticed this when running the tests locally as requested in the PR template), but that will need to be fixed before the PR can be merged. Additionally, please update your commit message to something more descriptive than `Update models.py`. I would think something along the lines `FIX: center in lognormal model can be negative`.

I'm at China and off work now. Git cloning from github is very slow at home. I will try to fix this tomorrow.

**Comment by reneeotten** [comment]
> How can I modify a commit message online on github? And i cannot revert the PR template. Should I close this and issue a new PR?

You probably cannot do that with the web-interface, at least I don't know how to do it. But don't worry about that for now - we can update the commit message when merging it (certainly no reason to close the PR!). Also, you don't need to do anything for the PR template now, in the future it would just be good to fill in everything.

> I'm at China and off work now. Git cloning from github is very slow at home. I will try to fix this tomorrow.

Sure, no worries! I will take a quick look later today to see why the test is failing and will report back here if I find something useful.

**Comment by newville** [comment]
@YoshieraHuang @reneeotten Thanks for the quick fix!  The test failure does look to be about the fit to the log-normal lineshape, but it seems odd that lifting the lower bound would cause that - I think it needs a closer look than I can give it right now.  If @YoshieraHuang has any challenges connecting to github, I would also be in favor of merging this and fixing the commit message and investigating the test failures separately.  

That is, I would favor the mathematically correct but perhaps imperfectly-git-formatted improvement from a new contributor, and have us clean it up to our liking.   But, I defer to @reneeotten on this.

**Comment by reneeotten** [comment]
@newville sure we will certainly merge this PR and I can fix-up the commit message while doing so - no problem and @YoshieraHuang  doesn't need to worry about that part!

It doesn't hurt though to wait a day or two to see where the test-failure comes from and attempt to fix that at the same time. I do agree with you though that it seems weird that allowing `center` to be negative is causing a failure and it likely points to an already flaky test to start with...

**Comment by reneeotten** [comment]
@newville @YoshieraHuang after looking at the tests a bit, I think we should drop that test for now. I anyway still have the intention to rework the test-suite for `model.py`, `models.py`, and `minimizer.py` - so eventually I'll get to the `LognormalModel` and add some specific tests there.

It's a little strange to me anyway that what's done in the test is fitting a `LognormalModel` to a Voigt-like lineshape, which obviously doesn't fit very well, and then calculating the FWHM from the lineshape and comparing it with the model. If we want to do this, I think we should just do it for every lineshape using simulated data with some added noise... Before the change in this PR, the values just remained at their initial values, but now with allowing `center` to become negative, the final "best-fit" values are slightly different likely causing the test to fail.

I would suggest to merge this PR (and when doing so change the commit message a bit) and that I will push a commit removing the now failing test. Does that sound like a plan @newville ?

**Comment by newville** [comment]
@reneeotten Yes, I'm +1 on "drop the current suspicious tests and plan on fixing them (maybe soon, maybe in a little while) separate from this PR".

**Comment by reneeotten** [comment]
thank you @YoshieraHuang !

**Pull request merged**
