### PR TITLE
Reset to false the 'aborted by user flag' of Minimizer

### PR DESCRIPTION
**Pull request by azelcer**
#### Description
After a minimization is aborted by a callback returning True, the minimizer is left in an unusable state due to a flag not being reset (see issue #756). the only change is one-line change resetting the flag before starting a minimization.

###### Type of Changes
- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

lmfit: 1.0.2, scipy: 1.7.1, numpy: 1.20.3,asteval: 0.9.25, uncertainties: 3.1.6

###### Verification 
Have you
- [ ] included docstrings that follow PEP 257? -> No new classes, functions or methods introduced
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [ ] verified that existing tests pass locally?
- [ ] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [ ] added or updated existing tests to cover the changes? -> I still don't know the codebase well enough to do this
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example? -> See referenced issue

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten As I was looking at this, I was wondering if we should set `self.abort` to `False` in each of the solver methods, not just `Minimizer.minimize()`.   That is, if someone uses one of the methods other than `self.minimize`, the problem might still happen.  I think it's OK to merge as is, but maybe keep in mind that we could add more 'reset abort'.

**Comment by azelcer** [comment]
I agree that a complete check of all the places where this issue might lurk can take little longer, but I do not know the release policy.
I am no so familiar with all the fitting interfaces, but maybe a common internal resetting method could be implemented for all the ways of start a fitting. I leave that discussion for the mailing list.

**Comment by newville** [comment]
@reneeotten @azelcer +1 on moving to `prepare_fit()` method.

**Comment by reneeotten** [comment]
changes committed in bae3e0d206d135b0ce7c32f4478cd60d21030728 and e4f85a25ed2e6171fe7d7eea7e352609eb982f43 - thanks again @azelcer

**Pull request closed without merging**
