### PR TITLE
updates to examples gallery

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- improve layout of examples in the gallery (i.e., show output at the appropriate places, suppress unwanted text output) 
- use higher resolution figures (requires `sphinx-gallery >= 0.10.0`)
- use as much as possible defaults from `matplotlib`

- minor changes to plotting of residuals in `ModelResult.plot_residuals()`: show line in black, do not show label
- only return the `matplotlib.figure.Figure` instance in `ModelResult.plot()`

###### Type of Changes
- [ ] Bug fix
- [x] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.9.7 (default, Sep  6 2021, 12:38:33)
[Clang 12.0.0 (clang-1200.0.32.29)]

lmfit: 1.0.2.post111+g65fae85, scipy: 1.7.1, numpy: 1.21.2, asteval: 0.9.25, uncertainties: 3.1.6

###### Verification 
Have you
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  Thanks!  I haven't looked at the rendered results but am completely in favor of these cleanups and changes toward "standard, default matplotlib usage".

**Comment by newville** [comment]
@reneeotten I'd be happy to merge this and #754 and #755 if you agree.  Do you think the test problems are all from this timing issue?

**Comment by reneeotten** [comment]
@newville I've rebased this with current `master` and added a few more small corrections (i.e., typos and consistent spelling) in the documentation/examples. This should all pass and if it does I would be happy to merge this; of course if you want feel free to build the documentation first and take a look at the changes before pushing the button. 

I have one more PR lined up which isn't completely done yet, but after that I think we should be ready to tag a release. I would say by the end of this weak at the latest, but I'm hoping to get the last few things figured out today/tomorrow.

**Comment by newville** [comment]
@reneeotten Great - thanks!  And sorry you had to rebase this.  I'll merge this now.  Maybe we can start compiling release notes and doc updates for tagging 1.0.3?

**Comment by reneeotten** [comment]
> @reneeotten Great - thanks! And sorry you had to rebase this. I'll merge this now.

no worries - that only takes 30 seconds ;)

> Maybe we can start compiling release notes and doc updates for tagging 1.0.3?

I think I've kept track of these things and updated the `whatsnew.rst` for the 1.0.3 release - but please do read through them and see if I missed anything.

There is a bit of clean-up possible still with stuff that we deprecated in v0.9.12 and/or v0.9.13 (i.e., more than 2 years ago) so I would like to do that still. I tried to update the CI to test with the released version of Python 3.10, but it seems that it will take about a week before that's available through Azure pipelines. So for now we just keep that being installed as `Python310_dev` even though that is the released version. I will update then once it's available, but this anyway has nothing to do with the release.

**Pull request merged**
