### PR TITLE
PR to make lmfit PY3-only

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR is intended to collect the changes needed to remove compatibility-code for Python 2.7 and to make use of new language-features in PY3 (see #544).

This initial changes were mainly prompted by using the ```pyupgrade``` pre-commit hook after adding the ```py3-plus``` flag. If we decide to also drop support for Python 3.5 we can likely make some more changes (i.e., no need for ```OderdedDict``` anymore, we can use ```f-strings```, ....). 

I'd suggest to use this PR to discuss the possible changes and just keep committing here until it's all done. We can clean-up the commit history before merging this PR, which should anyway happen after we release version ```0.9.15```.  

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.7.5 (default, Oct 18 2019, 21:19:21)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 0.9.15rc1+5.g7076e19, scipy: 1.3.3, numpy: 1.17.4, asteval: 0.9.17, uncertainties: 3.1.2, six: 1.13.0

###### Verification 
Have you

- [x] included docstrings that follow PEP 257?
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [ ] added or updated existing tests to cover the changes?
- [x] updated the documentation?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Awesome!  Yes on using this to merge into master to become 1.0.   I don't see anything obvious missing.

I am OK with not supporting Py3.5  From https://devguide.python.org/#status-of-python-branches:

Py3.5 is on "security fixes only" with end-of-life in September 2020.   With our typical rate of releases would mean it misses one or two releases, but at months before end-of-life when 3 newer versions exist.  So, I don't know who would be "stuck" with Py3.5 and lmfit 0.9.15, but it would only be for a few months with lots of upgrade options.
 
Py3.6 would allow us to drop OrderedDict as the basis of Parameters - that would be profound enough that it would justify dropping Py3.5 a bit early.  Having f-strings available would be very helpful.   Sadly, I think we're not really able to get performance improvements using `async` routines here.

I'm now +1 on dropping Py3.5.

**Comment by reneeotten** [comment]
> Py3.6 would allow us to drop OrderedDict as the basis of Parameters - that would be profound enough that it would justify dropping Py3.5 a bit early. Having f-strings available would be very helpful. Sadly, I think we're not really able to get performance improvements using `async` routines here.

For moving to ```f-strings```, I do think that improves readability and is therefore useful. I would suggest to move at the same time away from the ```%``` notation. Some of that was done automatically by the ```pypupgrade``` hook, but I will carefully go through the code and try to cover all of this.

From the Python documentation it seems that dictionary being ordered is only a *language feature* since PY3.7, but indeed it has been around in PY3.6 as a side-effect. So I guess we could rely on it there already; do you want try this @newville and if it works add these changes to this PR?

**Comment by newville** [comment]
@reneeotten Yes to all that.   I have to force myself to use f-strings, but I'm +1 on converting.
And I am totally willing to assert that dictionaries are ordered in Python3.6 and later.    Once they introduced that, there was never going to be any chance of going back.  The fact that they had a moment's hesitation is understandable, but they quickly came to their senses.

**Comment by reneeotten** [comment]
@newville okay, I pushed a new branch called ```python2``` which is the same as the current ```master```. I think we should make this (and likely ```master``` a "protected branch") so that they cannot be deleted and it would be good to disallow things like force-pushing as well. I don't have much experience with these settings though, so if anything I would need to look at the documentation and/or experiment a little bit first on my own repository before doing any of this on the ```lmfit``` one. Alternatively, if you have explored these options before perhaps you can just do this.

I pushed to this PR with the changes to make it PY3-only, but still compatible with Python 3.5. To make all the changes with respect to the ```f-strings``` and ```OrderedDict``` will likely take more time, and I don't have much of that left before leaving for the holidays. So I would consider this PR ready-to-go, and if you want you could release a PY3-only version of ```lmfit``` from this. I might have some time to work on this a bit and perhaps get a PR for PY36+ but I cannot promise a timeline here, it could as well be towards the end of January... Of course, if you get snowed in and want to make these changes yourself feel free ;)

**Comment by newville** [comment]
@reneeotten OK thanks!   I turned on the default branch protection rules for `python2` but did not see an obvious regex that worked to mean "`python2` or `master`".    To be continued...

I expect to have some time this week to work on getting 1.0 out.   I think the main question is "Do we promise Py3.5 support in lmfit 1.0 or not?"   I am about +0.25 on "Py3.6+ only", so I would really like to hear your opinion (and anyone else's).

Saying it is Py3.6+ only doesn't mean we have to convert everything to f-strings now for 1.0, just that we can do that going forward and don't guarantee Py3.5 support.   If we agree on Py3.6+ only, I would try to move from OrderedDict to plain Dict for 1.0, but I think that would actually not be very hard to do (assuming it all works).

I also wonder if we should add a deprecation for `Minimizer.emcee` for 1.0.  I think we should remove this eventually, and so deprecate it soon.  Should we do that now?  Again, I lean "yes", but only slightly.

If I don't hear from you, I'll keep Py.3.5 support and not deprecate `Minimizer.emcee`, and still try to get a release out around Dec 20 or so.

Anyway, thanks for doing all this, and have a great holiday!

**Comment by newville** [comment]
OK, merging this to master!

**Pull request merged**
