### PR TITLE
Fix Pearson7 FWHM

### PR DESCRIPTION
**Pull request by openafox**
Running test with #435 revealed the fwhm parameter for Pearson7 was incorrect. Went through the derivation and found this which check good.

### CODE REVIEW

**Comment by newville** [comment]
@openafox I applaud the effort.  Would you be willing to make a single PR with as many height/fwhm etc calculations as you think are needed?   And please include docstrings as appropriate and some unit tests.

**Comment by openafox** [comment]
@newville I am working on the derivations for the rest of the peak like functions as I have time. Will make a PR in the next week.

**Comment by newville** [comment]
@openafox  Any progress on this PR?  I fear I may have made too much work for you, and now there is a small conflict with "missing" vs "nan_policy".   Any chance of resolving this?  Thanks,

**Comment by openafox** [comment]
@newville I have been busier than I anticipated. I am through derivations for about half of them. We could close this PR and I will open a new one in the next few weeks with them all.

**Comment by newville** [comment]
@openafox OK, I completely understand!

**Pull request closed without merging**
