### PR TITLE
Improve test-coverage and a few other small updates

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
A few updates in this PR:
- improve test-coverage and/or add more explicit testing of functions
- update the ```pre-commit``` hooks
- fix the encoding for arrays with dtype=object (in ```jsonutils.py```)
- remove references to Python 2.7 from a few docstrings

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Test-suite

###### Tested on
Python: 3.8.2 (default, Feb 27 2020, 15:26:21)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 1.0.0+12.gdbe55c5, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2

###### Verification 
Have you
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] added or updated existing tests to cover the changes?

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville I struggling a bit to understand some code (i.e., the ```__setstate__``` method in ```parameters.py```) that you added about a year ago or so in PR 554. In particular the code in the ```if isinstance(val, dict):```-block. That does not get executed in any of the tests and I have a hard time understanding when this ```if```-statement would be true. Do you remember why this was added and is there a test-case that we can add where the code is executed and we can make sure the outcome is correct?

**Comment by newville** [comment]
On Sat, Feb 29, 2020 at 10:09 PM Renee Otten <notifications@github.com>
wrote:

> @newville <https://github.com/newville> I struggling a bit to understand
> some code (i.e., the __setstate__ method in parameters.py) that you added
> about a year ago or so in PR 554. In particular the code in the if
> isinstance(val, dict):-block. That does not get executed in any of the
> tests and I have a hard time understanding when this if-statement would
> be true. Do you remember why this was added and is there a test-case that
> we can add where the code is executed and we can make sure the outcome is
> correct?
>
That part of the code is meant to try to cover the case of restoring a
json-dumped Parameters which has user-defined function in the asteval
symbol table.  It is sort of dependent on the details of what happens in
`jsonutils.encode4js`, which might be a little too fragile for longevity.
Maybe code to test for and unwrap special dictionaries holding complex
datatypes should all be in `jsonutils.py`.

It also looks to have a mistake, and that the code  should probably be

   for key, val in state['unique_symbols'].items():
            if key not in symtab:
                if isinstance(val, dict):
                    value = val.get('value', None)        ###  not
'__name__'
                    symname = val.get('__name__', None)
                    importer = val.get('importer', None)


> That is, it sort of looks like the current code could not ever work.  It
also looks like the importer is not checking the version string and raise
an exception on version mismatch - it probably should, though maybe "try
and explain failures with version difference" would be better.

If there isn't a test for this case of "dump/load Parameters with a
user-defined function", it should probably be added.
I don't think I'll have time to do that very soon.

**Comment by reneeotten** [comment]
@newville okay, I'll take a closer look at this some time next week. It seems to me that a [test-case was added as part of the PR](https://github.com/lmfit/lmfit-py/pull/554/commits/c6659fa4b900efea8a646b83831c3dbf12bb268f); however, it doesn't execute that part of the code...

**Comment by reneeotten** [comment]
@newville okay, I added a test-case and think I've fixed the code so that it will work properly with/without ```dill``` present. Unfortunately, without ```dill``` it does not completely work within the ```py.test``` framework, but to me all seems good in a "normal" Python interpreter. 
Can you please check the last commit and see if that makes sense to you and/or try it out on some of your real-life-examples? 

Also the ```set_expr_eval``` functions that is defined in the Parameter class is actually never called anywhere in the ```lmfit``` codebase; I've removed it.

**Comment by newville** [comment]
@reneeotten Thanks for the update and or adding the test. That makes it look like it is all working and much better.  I would be OK with saying that save/restore of parameters with user-defined symbols requires using `dill` for both save and restore.  FWIW, I do think that we really cannot guarantee that save/restore to work between Python versions.

Anyway, is this ready to merge? I'm +1.

**Comment by reneeotten** [comment]
> I would be OK with saying that save/restore of parameters with user-defined symbols requires using `dill` for both save and restore. FWIW, I do think that we really cannot guarantee that save/restore to work between Python versions.

I think it will work correctly now even without ```dill``` being present at least for saving/restoring with the same Python version. (I'm pretty sure there is a way to make this one test work with ```py.test``` in the absence of ```dill```, but haven't figured yet out how). But indeed, if at some point bug-reports starty pouring in about it not working, we could just require ```dill``` for save/restore of Parameters/Models/ModelResults. But I guess nobody has really used the save/restore feature for Parameters as nobody complained about it and it isn't working currently (at least without ```dill``` installed).

> Anyway, is this ready to merge? I'm +1.
As far as I am concerned it is. I'll continue a bit more on the test-suite and once that's done move on with transitioning to ```f-strings``` and other Python 3.5+ (or even 3.6+) features.

**Comment by newville** [comment]
@reneeotten  OK, merging this - Thanks very much! 

 I'm +1 on dropping Python 3.5 (and relying on dicts being ordered and f-strings) in the master branch at any point now.

**Pull request merged**
