### PR TITLE
update whatsnew, add discussion of data coercion

### PR DESCRIPTION
**Pull request by newville**
#### Description

updating docs, getting ready to tag v 1.2.0rc1

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on

Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]

lmfit: 1.1.0.post37+g97cf1f3, scipy: 1.10.1, numpy: 1.24.2, asteval: 0.9.29, uncertainties: 3.1.7

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [x] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten I'm seeing some "not-so-great rendering" results for the gallery examples when building the docs.  It looks like the current docs have some of this too: https://lmfit.github.io/lmfit-py/examples/example_use_pandas.html#sphx-glr-examples-example-use-pandas-py 

I have not investigated this in any detail, but I see the same on MacOS with Python 3.11 and (I think) the latest of all the sphinx and Jupyter-related packages.   Do you know what might be going on?

**Comment by reneeotten** [comment]
@newville I pointed this out in one of the earlier PRs. To me it seems it's only an issue for the "pandas" example. I haven't figured out why yet; I stripped that example to only a few lines and it still didn't render. I suspect it could just be because it's the first example and there is something not right with our template or so... I haven't checked the Sphinx version yet - might have some time tonight to take a look.

**Comment by newville** [comment]
@reneeotten ah, thanks.  That example seemed to render a better for me on windows (py311, from mambaforge, a different test setup). I hope that is not required, but we could push results built that way if it comes to that ;)


It also seems like sometimes the output appears before the input script.   That seems more like "that's kinda weird" than an obvious problem.

**Comment by newville** [comment]
@reneeotten any objections to merging this and tagging 1.2.0rc1?

**Comment by reneeotten** [comment]
@newville nope, sounds good to me! We can figure out the documentation/gallery issue later - it isn't worse than the current situation.

**Comment by newville** [comment]
@reneeotten I think that ``filter_spurious_links` was the problem.  I'll merge this

**Comment by newville** [comment]
Yea, I did check that it worked better on locally-built docs, but thought that I should verify that the CI could build the docs.  I'm OK with either removing the script or leaving it there unused until we convince ourselves that it is not needed.   At the moment, I'm ok with saying "it seems to not be needed anymore", but maybe there is a situation or version of sphinx-gallery that needs (or needed) it.

**Pull request merged**
