### PR TITLE
Add test for bug #271

### PR DESCRIPTION
**Pull request by tritemio**
asteval and add_param_hint() error

### CODE REVIEW

**Comment by tritemio** [comment]
Fixed test and rebased.

**Comment by newville** [comment]
Thanks!

**Comment by tritemio** [comment]
This was not merged in master.

**Comment by newville** [comment]
@tritemio  Oh.  I merged this into *model_conf_interval*, and then merged that into master.   I thought that was supposed to "work" (that is, alter the mode_conf_interval branch, then get into master).   Some subtlety of git workflows?  

Dunno.   Should we try that again?

**Comment by tritemio** [comment]
I went to Branch,  switched to model_conf_interval branch and made a PR against master. Seems ok.

**Comment by tritemio** [comment]
xref  #274

**Comment by newville** [comment]
@tritemio Thanks and sorry for the mix up.  I should have checked what those merges did!    I just assumed that the magic of github would take care of everything.

**Pull request merged**
