### PR TITLE
True calc of Voigt height

### PR DESCRIPTION
**Pull request by openafox**
The current estimation of Voigt height can be off by a significant amount. This will calculate the true value. Docs already state height is included.

### CODE REVIEW

**Comment by newville** [comment]
@openafox should these values for height calcs be tested?

**Comment by openafox** [comment]
@newville Ok. I created a general test [function](https://github.com/openafox/lmfit-py/blob/24e5058014ac004e10dde44d6e0c639c2fecd2f0/tests/test_height_fwhm.py) and it looks good.

**Comment by newville** [comment]
@openafox  Great, and fast.  That will be very helpful.

**Comment by openafox** [comment]
@newville Should I PR the function?

**Comment by newville** [comment]
Yes please do.

**Pull request merged**
