### PR TITLE
CI: attempt fix Python 3.10-dev build

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR attempts to fix the build of Python3.10-dev on Azure. For some reason Azure pipelines doesn't run when pushing it to my GitHub account, so testing a PR here.... Please do NOT merge yet ;)

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [ ] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by reneeotten** [comment]
I am not sure how to fix this yet... it seems to be happening with a newer version in the Python 3.10 development cycles (`pip` appears to be the same version when it still worked and now). Hopefully this will be fixed again or documented on what has changed. To be continued at some later time...

**Comment by newville** [comment]
@reneeotten Thanks for looking into this!  If I read the Azure messages correctly (still pretty new to Azure), it looks like Python3.10 isn't really supported yet.

**Comment by reneeotten** [comment]
> @reneeotten Thanks for looking into this! If I read the Azure messages correctly (still pretty new to Azure), it looks like Python3.10 isn't really supported yet.
..
@newville yes but that has never stopped us before ;) I think the required changes have just landed upstream at `pip` so I wanted to try this again, but I seem unable to reopen this PR - might have to open a new one instead..

**Comment by newville** [comment]
@reneeotten For an unrelated project that had "fix CI from very old unittests and Travis+Docker Image config", I spent quite a bit of time trying to get Azure Pipelines to work, only to basically give up when Azure would not run the jobs. But then since I had the "what to install, and how to run the tests", I tried out Github Actions, and that went amazingly smoothly and runs very fast.  

Just as a simpler comparison, I then converted `asteval` from using Azure to Github Actions and it seems way easier for a simple project.    This is at https://github.com/newville/asteval/blob/master/.github/workflows/test-python.yml   The results are faster and easier to navigate.  FWIW,  I think I may need to fix the push to codecov.io, but that's sort of a separate issue.

I don't know if Python 3.10-dev is yet supported, but using Actions might make life much easier in general. It looks like Actions could also be used to deploy docs (possibly as a separate Action from RunTests), push to PyPI, etc.   
Any thoughts on this? There's no rush on any of this, but I think it is worth considering.

**Comment by reneeotten** [comment]
@newville I am sure that GitHub Actions would work as well. To be honest I don't see really that the GitHub Actions workflow configuration is that much easier; we (or at least I) would still want to do the `pre-commit` checks, build for `current`/`minimum` dependencies, run the tests for the Python development version, and build the documentation. 

I think one can also deploy docs, push to PyPI and so on with Azure. I just haven't looked into that since we want (I think) to only upload the docs once we release a stable version anyway; that (and therefore also uploading to PyPI) doesn't happen so often that there would be a real time saving here I think.

I'd conjecture that replicating the current Azure pipeline in GitHub Actions would give a similar configuration file as the required fields appear pretty much the same. If you want to try and replicate our current setup in GitHub Actions because you like the output better than Azure that's fine with me; I have no strong preference either way. It's just that I spent enough time getting Azure to work in the way I wanted it and don't really feel like investing time in switching CI providers again.

**Comment by newville** [comment]
@reneeotten OK thanks. Yes, I agree that the scripts are not all that much different of a script, but somewhat easier navigation for the results. 

Actions also makes it clear that there can be multiple separate actions -- testing, doc generation, deployment.  I imagine that could be done with Azure too.  But for me, the real feature was that Azure refused to run tests for a new project, giving an error message of::

    No hosted parallelism has been purchased or granted. To request a free parallelism grant, 
    please reach out to azpipelines-freetier@microsoft.com with your name and organization name

I filled out the form, twice.  Still no access.  So I deleted the project on Azure and moved to Github Actions.  That worked remarkably well.   I've since removed asteval and one other project from Azure, and will remove one more soon.

**Pull request closed without merging**
