### PR TITLE
feat: add ODR solver

### PR DESCRIPTION
**Pull request by JeppeKlitgaard**
This adds an ODR solver using `scipy.odr`. This is WIP and because of the very different approach used in `scipy.odr` to the other scipy minimizers it requires access the fitting data in a different way which is currently 'hacked' around.

I probably won't have time to finish this work anytime soon, but wanted to leave it here for myself or others to pick up in the future. Adding ODR support is surprisingly simple.

Nothing below this line has been filled out just yet – this is a draft!
---

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [ ] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by JeppeKlitgaard** [comment]
@newville Let me know your thoughts on this. I don't have a lot of time to commit towards this, but I think it could be a valuable addition.

Since this was primarily a dirty hack for my own use-case, it doesn't fit with older Pythons in its current form. This could be amended easily.

**Comment by newville** [comment]
@JeppeKlitgaard  You call this a draft and a dirty hack and have no tests, examples, or docs. Your code fails with import errors in our tests. From a quick look, I would be cautious about the typing here, and the black-like function signature does not match our coding style.

But you also say that you do not have a lot of time to work on it. Are you expecting someone else to add docs, tests, and examples and then support this code?

**Comment by JeppeKlitgaard** [comment]
I was more wondering whether you would be open to adding ODR support or not – it should be noted that it requires a bit of a work-around since the ODR interface requires access to the data rather than just minimizing a function.

I realise this isn't done and lacks tests, docs, etc – hence being marked as a draft.

The type hinting was primarily added for my own benefit during development and can be removed later if need be. I would potentially be open to working on this PR at a later point if there is appetite for it

**Comment by newville** [comment]
> I was more wondering whether you would be open to adding ODR support or not – it should be noted that it requires a bit of a work-around since the ODR interface requires access to the data rather than just minimizing a function.

I don't think anyone would object to adding support for ODR to lmfit.  Doing so seems like a fair amount of work.  I have not looked closely at the changes you have made, and if this is meant to be a "draft", then I am not sure about your commitment to this effort.

> I realise this isn't done and lacks tests, docs, etc – hence being marked as a draft.

Well, you could have asked a question about this on the mailing list, or on the Github discussions page (or commented on the related discussion at https://github.com/lmfit/lmfit-py/discussions/789).  But, you created a PR - a proposed addition to the code and presumably a proposed solution to a problem (often, but not always, explicitly stated in an Issue).   There is sort of a normal workflow to these things.  A random dude on the internet tossing some unfinished, undocumented, untested code, and saying "here you go, I don't have time to work on this" is not our preferred mode of working.

> The type hinting was primarily added for my own benefit during development and can be removed later if need be. I would potentially be open to working on this PR at a later point if there is appetite for it

I don't have a strong opinion on type hinting in general: it adds value but it is more code to maintain and test, and think about. In this specific case, I am unsure whether the type hints are actually correct.   The black-like code formatting will need to change.

**Comment by newville** [comment]
@JeppeKlitgaard @reneeotten We are 4 months from this initial, non-working draft which then got no attention. 

I think we should close PRs that go several months without activity or discussion.

**Comment by JeppeKlitgaard** [comment]
> @JeppeKlitgaard @reneeotten We are 4 months from this initial, non-working draft which then got no attention.
> 
> I think we should close PRs that go several months without activity or discussion.

I agree. I just finished exams and may get around to having another look at this, but I have closed the PR for now.

**Pull request closed without merging**
