### PR TITLE
ensure that correct initial params are used when re-fitting a ModelResult

### LINKED ISSUE #960: ModelResult.fit() does not use provided params
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
When using ModelResult.fit() the provided params are not being used as the initial values.
In the below example, result_leastsq.params shows that result_brute.params was used as the initial values rather than the params provided.
result_leastsq.init_params does report the correct values.

###### A Minimal, Complete, and Verifiable example
```
import numpy as np
import lmfit
import copy

x = np.linspace(-10, 10, 100)
y = 3 * x**2 - 2 * x + 1 + np.random.normal(scale=10, size=x.size)

def quadratic(x, a, b, c):
    return a * x**2 + b * x + c

model = lmfit.Model(quadratic)
params = model.make_params(a=dict(value=1, min=-10, max=10),
                           b=dict(value=0, min=-10, max=10),
                           c=dict(value=0, min=-10, max=10),)
result_brute = model.fit(y, params, x=x, method='brute')
result_leastsq = copy.deepcopy(result_brute)
result_leastsq.fit(method='leastsq',params=result_brute.candidates[49].params)
```

###### Version information
Python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

lmfit: 1.3.1, scipy: 1.14.0, numpy: 2.0.0,asteval: 1.0.0, uncertainties: 3.2.1

### PR DESCRIPTION
**Pull request by newville**
This fixes #960 and #954.

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:35:23) [Clang 15.0.7 ]

lmfit: 1.3.1.post8+gb72cfb28.d20240713, scipy: 1.13.1, numpy: 1.26.4, asteval: 1.0.1, uncertainties: 3.2.2
###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [x] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [ ] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [x] added or updated existing tests to cover the changes?
- [ ] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten If you agree, I think squash-merging this would allow tagging and pushing version 1.3.2.

**Comment by newville** [comment]
@reneeotten I'm going to (squash) merge this and tag and push as 1.3.2

**Comment by reneeotten** [comment]
> @reneeotten I'm going to (squash) merge this and tag and push as 1.3.2

sorry @newville and thanks for fixing this! Between work and a newborn there isn't too much time for this at the moment... 😉

**Comment by newville** [comment]
@reneeotten No worries (I hear you!).  And also: Congratulations!

**Pull request merged**
