### PR TITLE
announce end of support for Python 2.7

### PR DESCRIPTION
**Pull request by newville**
Change `doc\installation.rst` to clearly state end of support for Python 2.7

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville I have a branch with release notes and some minor (style) changes that I added this afternoon. Do you want me to add these commits here?

**Comment by newville** [comment]
@reneeotten sure -- I was just starting to go through the commits but got sidetracked by other events... If you have a start of Release Notes that would be great!

**Comment by newville** [comment]
@reneeotten Thanks - that looks great.  I'll tag as rc1 later today unless there are objections, and will expect to release as 0.9.15 a few days after that.

**Comment by newville** [comment]
OK, merged this, tagged 0.9.15rc1, pushed tarball to PyPI, updated github-pages docs.

**Pull request merged**
