### PR TITLE
Add the run_mcmc_kwargs argument to Minimizer.emcee

### PR DESCRIPTION
**Pull request by rbnvrw**
#### Description

The [`emcee.EnsembleSampler.run_mcmc`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.run_mcmc) function that is used in `Minimizer.emcee` passes keyword
arguments to the [`emcee.EnsembleSampler.sample`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.sample) function. Several of these keywords could be useful to change, for example,
`skip_initial_state_check` or `tune`.

In order to facilitate this, I have added an optional parameter to `Minimizer.emcee` called `run_mcmc_kwargs`,
which is a `dict` that will be passed to the `emcee.EnsembleSampler.run_mcmc` function. In this way,
all extra keyword arguments are supported and this code does not need to be updated when extra keyword arguments
are added to `emcee.EnsembleSampler.run_mcmc` or `emcee.EnsembleSampler.sample`.

###### Type of Changes

- [ ] Bug fix
- [x] New feature
- [ ] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on

Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

lmfit: 1.0.1+135.g709757d, scipy: 1.5.2, numpy: 1.19.1, asteval: 0.9.21, uncertainties: 3.1.4

###### Verification 
Have you

- [x] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list? **I think this is not necessary because this was my own idea and I've described it above.**

- [x] verified that existing tests pass locally?

- [x] verified that the documentation builds locally?

- [x] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes? **I think this is not necessary because it is a very small change, that only passes on keyword arguments. It is covered by the existing tests.**
- [x] updated the documentation? 
- [ ] added an example? **I think this is not necessary because it is a very small change.**

Please let me know if I need to make changes / you have any questions. And thanks for this awesome package!

### CODE REVIEW

**Comment by rbnvrw** [comment]
The build is failing only for Python nightly, the rest of the builds have passed and the error seems to be unrelated to the change I've made.

**Comment by newville** [comment]
@rbnvrw Shrug.  I have to admit that I am not ever going to be excited about more support for `Minimize.emcee`.  Does anyone else have an opinion on this? 

The test failure is from the check of how much of the code is tested.  You added code, including to check that this new argument is a dict, but did not add any tests for the new code.  That seems like a reasonable complaint to me.

**Comment by rbnvrw** [comment]
> @rbnvrw Shrug. I have to admit that I am not ever going to be excited about more support for `Minimize.emcee`. Does anyone else have an opinion on this?

Thank you for your (unfortunately less than enthusiastic) reply @newville. I'm not sure why you don't want to add more support for emcee? In my opinion it is a very useful tool to obtain reliable estimates of the posterior probability distributions and I think lmfit is a nice interface to it. Judging from [the citations to their article](https://badge.dimensions.ai/details/id/pub.1006523726), emcee is widely used in the scientific community.
 
> The test failure is from the check of how much of the code is tested. You added code, including to check that this new argument is a dict, but did not add any tests for the new code. That seems like a reasonable complaint to me.

Should I fix this or is this a waste of my time?

**Comment by newville** [comment]
@rbnvrw   My lack of enthusiasm about `Minimizer.emcee` is mostly that is not a minimization method.  Essentially of the other methods in `Minimizer` wrap methods that solve minimization problems.  So, while useful for exploring parameter space,   `Minimizer.emcee` is just misplaced by being in `Minimizer`.  We have other tools for exploring parameter space and confident intervals after a fit is done that are separate from the `Minimizer` class.

This is further complicated because the `emcee` project is itself less than forthcoming - or perhaps just confused - about whether it considers itself to be appropriate as a minimization tool. From the front page of their documentation (https://emcee.readthedocs.io/en/stable/tutorials/line/) there is a tutorial titled "Fitting a model to data" that begins with "If you’re reading this right now then you’re probably interested in using emcee to fit a model to some noisy data. On this page, I’ll demonstrate how you might do this...".   Now, I find the example shown to be flawed in that the simulated non-stochastic noise is clearly cooked to make the difference in results as large and favorable to MCMC as possible, but that's a relatively small point.  My main objection is just that they **say** more than once that `emcee` is fitting a model to this data.  That is simply not true.  It is not what `emcee` is designed for or even capable of doing, and it is not what the sample shows.  This tutorial is not new, it is not "in development".  It is a prominent part of their documentation.  It is not a mistake, it is not an exaggeration, it is not an error that accidentally slipped in.  You might be charitable and call it wrong, or you could be honest and call it a lie.

I am frequently reminded of how valuable the `emcee` is.  (As it turns out, I do not find "highly cited" that persuavise) For sure, I agree that MCMC methods are good for exploring parameter space after a fit is done.   Is `emcee` good at that?  Probably - I have no objection to using it for that.  But the implication by them (and by extension, lmfit, especially with the code in lmfit effectively being a "minimization method") that it is useful for doing the job of fitting data to a model.  And that is wrong.

So, I have been persuaded to not remove the `emcee` using code from lmfit.  It should be moved out of `minimize`.  I have no intention adding my name to any commits that appears to continue the lie that `emcee` is useful for fitting data. 

I'm sure that gives you no insight on whether it is worth your time to add tests about added keyword arguments.  And I apologize for this being so long - I did not want to waste time trying to make it shorter.

**Comment by rbnvrw** [comment]
Thank you @newville for the detailed answer! I agree with your point of view.
However, it seems to me that (as you also state) the emcee routines are still valuable to include in lmfit. If I understand it correctly, your only problem lies with managing user's expectations as to what it should be used for exactly.
Are there any efforts / ideas concerning moving the emcee routine from Minimizer to another place in lmfit?

**Comment by newville** [comment]
@rbnvrw Yes, I agree with everything you say:  MCMC is for sure a valuable approach.   `emcee` is a good implementation of MCMC, and we should help `lmfit` users to use this.   

Maybe I should look into moving `emcee` out of `Minimizer` - it seems that would address my concerns and allow its use to move forward.   I am not sure I have a lot of time to dedicate to this, but I will look into this.

**Comment by reneeotten** [comment]
@rbnvrw @newville I agree with your statement that `emcee` isn't really a fitting method, but should be used *after* a fit is performed or you need to supply really good starting values. And yes, I was/am of the opinion that it is useful and would like to keep it in `lmfit`.

Considering that it should be used after an actual fit, moving it out of `Minimize` is worth considering. However, it is quite convenient to have it return a `MinimizerResult` and use the same input/syntax as for other actual fitting methods. That does make the user-experience better I think, and it would require some thinking/work to move it without having to duplicate a lot of code as it uses quite a bit of code in the Minimizer class. But I see your point that we have the code for confidence intervals separate as well, so it can be done.

If we keep the status quo (long term or short term), then we could consider this PR but perhaps we should use then `fit_kws` to pass options to the underlying method, just as we do for other minimizers?

**Comment by newville** [comment]
@reneeotten Yeah, I agree that returning a MinimizerResult would be the least disruptive change (though it's also true that MinimizerResult is not very complex - one of the few methods/properties is specific to using `emcee`).    But like the confidence-interval code (a closer analog), I expect that an `emcee` wrapper should take a MinimizerResult (or ModelResult) as an argument, and return a MinimizerResult (or maybe some new Result class??).   

Anyway, I just started looking at this and am not planning to do anything quickly ;).  So thanks, and more suggestions definitely welcome.

**Comment by newville** [comment]
@rbnvrw @reneeotten I'm going to merge this, in hopes of getting to version 1.0.2 soon(ish).

**Pull request merged**
