### PR TITLE
DOC: last changes for new release

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
A few small changes to the documentation, making this -hopefully- ready for a new release:
- update `whatsnew.rst` and link the version number in the sidebar to that document
- link to EPUB/PDF/HTML documentation on `gh-pages` instead of `https://cars9.uchicago.edu/software/python/lmfit/`
- update `publish_docs.sh` to build all documentation on `master`, then switch to `gh-pages`. Once on that branch clean-up all the old files first, unpack the latest documentation, and commit with adding the latest `tag` to the commit message. After checking that the commit is indeed correct it can be pushed to `upstream`. 

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.9.1 (default, Dec  8 2020, 20:10:16)
[Clang 12.0.0 (clang-1200.0.32.27)]

lmfit: 1.0.1+161.gc8ed043, scipy: 1.6.0, numpy: 1.20.0, asteval: 0.9.21, uncertainties: 3.1.5

###### Verification 
Have you
- [x] verified that existing tests pass locally
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?

### CODE REVIEW

**Comment by Tillsten** [comment]
Thanks for all that work! If possible, I would like to have also badge linking to the documentation.

**Comment by reneeotten** [comment]
> Thanks for all that work! If possible, I would like to have also badge linking to the documentation.

I am not sure I understand what you mean with this... I assume you want a link to `https://lmfit.github.io/lmfit-py/`, but where should this link be?

**Comment by newville** [comment]
@reneeotten great!! merging....

**Comment by reneeotten** [comment]
@Tillsten okay, I added a badge to `README.rst` linking to the documentation on GitHub Pages. I *think* that is what you intended with your comment - correct? Please take a look and let me know.

**Comment by Tillsten** [comment]
Perfect! Thanks again.

**Comment by newville** [comment]
@reneeotten Oh yeah, that's very nice.

**Pull request merged**
