### PR TITLE
DOC: updates/fixes to layout and building of documentation

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
The layout of the HTML documentation doesn't look so good, see figure below: 

image

whenever there is a code block (this is just one example), the remainder will only continue below the right-hand sidebar). I have tried many things in the current template but cannot get it fixed and it seems that our custom template is a bit fragile. So I propose to use an "official" Sphinx theme (in fact, the `sphinx13` theme that they use for their own documentation); we'll know for sure that with new updates they'll either fix the theme or make sure that it doesn't break ;) 

Of course, the change of the template does result in a slightly different layout and color-scheme of the documentation (see below). 

image

I personally like the outcome, but am not at all set to the colors and such so if someone wants to change things please be my guest (I am  not so good with CSS or interested for that matter...).

This PR contains the following:

- vendor and use sphinx13 theme and basic/layout.html
- update both for lmfit: show menu also on index page, do not show link to source file in sidebar, center titles in indexsidebar.html
- require sphinx-gallery >= 0.8 ; this automagically filters `matplotlib` warnings
- minor cleanup docstring for SineModel
- fix building epub, suppress warning about unknown mimetype
- revert "DOC/STY: fix issues reported by rstcheck pre-commit hook", which broke the PDF/EPUB generation
- use sphinxcontrib-svg2pdfconverter and cairosvg for converting images instead of ImageMagick (also better quality)
- filter out links to Gallery index from examples
- test building all variants for documentation on Travis CI
- fix DeprecationWarnings in examples 

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [x] Documentation / examples

###### Tested on
Python: 3.9.1 (default, Dec  8 2020, 20:10:16)
[Clang 12.0.0 (clang-1200.0.32.27)]

lmfit: 1.0.1+104.g0ca64ab, scipy: 1.5.4, numpy: 1.19.4, asteval: 0.9.21, uncertainties: 3.1.5

###### Verification 
Have you
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Thanks very much, that looks good to me!  FWIW, long ago I really did not like the default sphinx theming, but that has all changed these days.  My CSS/HTML skills haven't gotten any better since about 2005, so I basically no business having an opinion.;)  I could easily be persuaded to switch to any of the "standard" or "supported custom" sphinx themes.  

Honestly, I barely have time or energy for this project.  Just trying to keep up with questions is sort of exhausting.  So anything that would make it easier for someone else to work on seems like a good idea to me.

**Comment by reneeotten** [comment]
> @reneeotten Thanks very much, that looks good to me! FWIW, long ago I really did not like the default sphinx theming, but that has all changed these days. My CSS/HTML skills haven't gotten any better since about 2005, so I basically no business having an opinion.;) I could easily be persuaded to switch to any of the "standard" or "supported custom" sphinx themes.

I think this theme would work well and wouldn't be much time to maintain or anything, so I would be in favor of using it. The contents is still the same so people should be good to find things... I just noticed that I missed the "Least-Squares" part in the title, so let me remake that image tomorrow and push to this PR. We can let it sit for a few days to see if others have any comments or suggestions or it can just be merged - whatever you prefer.

**Comment by reneeotten** [comment]
I would consider this ready - comments/suggestions welcome!

**Comment by newville** [comment]
@reneeotten This looks really good to me.  There are a lot of very nice changes here.  It might be that someone would want to nit-pick some of these, but I think we should merge this and see if we want any additional tweaks once this is actually in place.

**Pull request merged**
