### PR TITLE
Minor code maintenance

### PR DESCRIPTION
**Pull request by reneeotten**
This PR contains some housekeeping on the codebase, mainly prompted by static code analysis. Most changes are minor, but please check at least the two below:

- remove the ```isclose``` function from ```parameter.py``` and use the (same) one from ```numpy```
- propagate the ```**kws``` argument to ```model.dumps()``` to ```json.dumps()```; at least from the docstring that seems to be the intention

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  these all look great to me.  I have no idea why we effectively had a copy on `np.isclose` in `parameter.py`.   And the `**kws` for `model.dumps()` looks like it should be there to me too.
Everything else looks very good.

The changes in `minimizer.py` might clash witth the changes from #512.  

I'm starting to think that #512 needs more time and that it should not delay releasing 0.9.12 but be targeted for 1.0.   Should we merge this and call it 0.9.12rc2 and then aim to release 0.9.12 in a week?

**Comment by reneeotten** [comment]
@newville I have a few more small doc/docstring changes that I'll try to finish up today, after that feel free to merge!

It does look like that PR will take indeed a bit of time to get correct. So I am fine with leaving that out and releasing 0.9.12 soonish. Alternatively, if you have a clear idea on how to make the ```_calculate_statistics``` function more general and feel like implementing that soon we could wait a bit. I think generalizing that function is the only hold-up for PR #512, all the other changes are quite trivial. But either way is fine with me, we can always release another version when there are sufficient improvements.

Next, I plan to look into a general way of adding the ```tqdm``` progress bar and work on re-organizing/re-writing the tests to make full use of ```pytest```.

**Comment by newville** [comment]
@reneeotten OK that sounds fine.  I do think we need think a bit about what the `calculate_statistics` code should do for 1.0.

I'll be on travel and in meetings most of this week, so won't have much time to look at this.

**Comment by newville** [comment]
@reneeotten OK, looks great -- thanks!

**Pull request merged**
