### PR TITLE
 FIX: do not override user-specified figure title in Model.plot() functions

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
As discussed on the mailing-list (see: https://groups.google.com/g/lmfit-py/c/3kxu8OYCAW4/m/61dhxzJkAgAJ) the automatically generate Model names are often not very suitable as figure titles for the Model.plot() functions. It should be possible to pass a `title` to `ax_kws` (or `ax_fit_kws`/`ax_res_kws`) depending on the plot function used; however, after the initialization of the `axes` it is overwritten with `ax.set_title` later.

Added a `title` keyword argument as well that allows for setting the figure title. If used, it will take priority over supplying a `title` to `ax_kws` (or `ax_fit_kws`/`ax_res_kws`).

###### Type of Changes

- [x] Bug fix
- [x] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.9.1 (default, Dec  8 2020, 20:10:16)
[Clang 12.0.0 (clang-1200.0.32.27)]

lmfit: 1.0.2+8.g5016da7, scipy: 1.6.0, numpy: 1.20.1, asteval: 0.9.22, uncertainties: 3.1.5

###### Verification 
Have you
- [x] included docstrings that follow PEP 257?
- [x] referenced existing Issue and/or provided relevant link to mailing list?
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] added or updated existing tests to cover the changes?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?
- [ ] added an example?

### CODE REVIEW

**Comment by reneeotten** [comment]
oh, never mind... this is possible already by given a `title` to `ax_kws`....

**Comment by reneeotten** [comment]
> oh, never mind... this is possible already by given a `title` to `ax_kws`....

actually, that doesn't work. You can supply `title` to `ax_kws` as in: ```ModelResult.plot_fit(ax_kws={'title': 'test'}``` and that should get passed to [pyplot.gca()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.gca.html`), but I think it's later overwritten by `ax.set_title(self.model.name)`. 

okay, this needs a bit more investigation and I don't have time for that right now... to be continued later.

**Comment by newville** [comment]
@reneeotten I think this is fine, and generally nicer than having to use `ax_kws` anyway.   My inclination is to just merge this....

**Comment by reneeotten** [comment]
> @reneeotten I think this is fine, and generally nicer than having to use `ax_kws` anyway. My inclination is to just merge this....

just to make sure... this still makes use of `ax_kws`, I did not actually add a `title` argument to the plot functions. It's just that using `ax_kws` before didn't work since the `title` was later in the code overwritten with a hard-coded value.

**Comment by newville** [comment]
@reneeotten oh, oops! I read the comments but skipped the code!   Yeah, I guess I would favor a `title=None` keyword argument, with `None` causing the automatic `self.model.name` to be used.  

FWIW, I would not be opposed to changing how `Model.name` was computed or overwritten, etc...

**Comment by reneeotten** [comment]
> @reneeotten oh, oops! I read the comments but skipped the code! Yeah, I guess I would favor a `title=None` keyword argument, with `None` causing the automatic `self.model.name` to be used.
> 
> FWIW, I would not be opposed to changing how `Model.name` was computed or overwritten, etc...

okay, I guess we can do both: fix the current issue with setting the title again irrespective if it was already set with the `ax_kws` **and** add a `title` keyword argument. I will update this PR tomorrow or in the weekend.

**Comment by newville** [comment]
@reneeotten sounds great!

**Comment by newville** [comment]
@reneeotten OK to merge this?

**Comment by newville** [comment]
@reneeotten I'll merge this before we get onto other stuff.  If this isn't a sufficient fix, we can revisit....

**Pull request merged**
