### PR TITLE
height param pseudovoigtmodel

### PR DESCRIPTION
**Pull request by openafox**
Add height parameter to pseudovoigtmodel based on equations in docs.

### CODE REVIEW

**Comment by newville** [comment]
@openafox Thanks -- that looks good.   Do we need to worry about the `sigma=0` ?  Probably not ... FWHM will not be a compelling question if `sigma=0`.

Anyone object to merging this?

**Comment by openafox** [comment]
min on sigma is already limited to 0 so no problem.

**Comment by reneeotten** [comment]
looks good to me - I guess this expression is a bit too complicated to rework to use the ```height_expr``` function...? Perhaps adding a sentence in the docstring as is done for other models about `fwhm` and `height` would be useful?

```In addition, parameters ``fwhm`` and ``height`` are included as constraints to report full width at half maximum and maximum peak height, respectively.```

**Comment by newville** [comment]
@openafox OK, looks good.  Thanks!

**Pull request merged**
