### PR TITLE
Improve pretty printing of Parameters

### PR DESCRIPTION
**Pull request by tritemio**
Similar to #318.

`Parameters` has a `pretty_print()` which prints with the following style:

```
Parameters({
    'p1_sigma': <Parameter 'p1_sigma', 0.03, bounds=[0.01:0.2]>, 
    'p1_fwhm': <Parameter 'p1_fwhm', 0.0706446, bounds=[-inf:inf], expr='2.3548200*p1_sigma'>, 
    'p2_sigma': <Parameter 'p2_sigma', 0.03, bounds=[0.01:0.2]>, 
    'p2_fwhm': <Parameter 'p2_fwhm', 0.0706446, bounds=[-inf:inf], expr='2.3548200*p2_sigma'>, 
    'p1_center': <Parameter 'p1_center', 0.3, bounds=[-0.1:0.7]>, 
    'p2_center': <Parameter 'p2_center', 0.85, bounds=[0.5:1.1]>, 
    'p1_amplitude': <Parameter 'p1_amplitude', 1, bounds=[0.01:inf]>, 
    'p2_amplitude': <Parameter 'p2_amplitude', 1, bounds=[0.01:inf]>, 
    'br_amplitude': <Parameter 'br_amplitude', 0.0001, bounds=[0:inf]>, 
    'br_center1': <Parameter 'br_center1', 0.3, bounds=[0:inf], expr='p1_center'>, 
    'br_center2': <Parameter 'br_center2', 0.85, bounds=[0:inf], expr='p2_center'>, 
    'br_sigma1': <Parameter 'br_sigma1', 0.03, bounds=[0:inf], expr='p1_sigma'>, 
    'br_sigma2': <Parameter 'br_sigma2', 0.03, bounds=[0:inf], expr='p2_sigma'>, 
    })
```

This follows a style typical for object representations in python (`__repr__`) but is hard to read for a user.

This PR modifies `pretty_print()` in backward-compatible way  (not removing arguments) in order to produce the following output:

```
Name               Value        Min        Max       Vary    Expr      
br_amplitude      0.0001          0        inf       True    None
br_center1           0.3          0        inf      False    p1_center
br_center2          0.85          0        inf      False    p2_center
br_sigma1           0.03          0        inf      False    p1_sigma
br_sigma2           0.03          0        inf      False    p2_sigma
p1_amplitude           1       0.01        inf       True    None
p1_center            0.3       -0.1        0.7       True    None
p1_fwhm        0.0706446       -inf        inf      False    2.3548200*p1_sigma
p1_sigma            0.03       0.01        0.2       True    None
p2_amplitude           1       0.01        inf       True    None
p2_center           0.85        0.5        1.1       True    None
p2_fwhm        0.0706446       -inf        inf      False    2.3548200*p2_sigma
p2_sigma            0.03       0.01        0.2       True    None
```

### CODE REVIEW

**Comment by newville** [comment]
@tritemio  Very Nice!    But can you include  `stderr` as well?

If space limit is a concern, I'd suggest considering compressing `Min` and `Max` (which will rarely use all available space), and possibly make a `Bounds` column that looks like  `[0:inf]`, say by doing something like (around line 250)

```python 
pvalues['bounds'] = '[{}:{}]'.format(values.min, values.max))
````

then formatting that with '{bounds:>12}' or something similar.   But that's just a suggestion....

**Comment by danielballan** [comment]
Nice!

**Comment by tritemio** [comment]
Instead of special-casing min/max columns I made the printed columns configurable.

Default:
```python
>>> params.pretty_print()
Name             Value      Min      Max   Stderr     Vary     Expr
br_amplitude    0.7783        0      inf  0.05306     True     None
br_center1      0.3514        0      inf 0.004943    False p1_center
br_center2      0.8595        0      inf  0.01015    False p2_center
br_sigma1       0.1222        0      inf 0.004688    False p1_sigma
br_sigma2       0.0748        0      inf 0.008535    False p2_sigma
p1_amplitude    0.5845     0.01      inf  0.02009     True     None
p1_center       0.3514     -0.1      0.6 0.004943     True     None
p1_fwhm         0.2878     -inf      inf  0.01104    False 2.3548200*p1_sigma
p1_sigma        0.1222     0.01      0.2 0.004688     True     None
p2_amplitude    0.2016     0.01      inf   0.0227     True     None
p2_center       0.8595      0.5      1.1  0.01015     True     None
p2_fwhm         0.1761     -inf      inf   0.0201    False 2.3548200*p2_sigma
p2_sigma        0.0748     0.01      0.2 0.008535     True     None
```
Only selected columns:

```python
>>> pretty_print(columns=['value'])
Name             Value
br_amplitude    0.7783
br_center1      0.3514
br_center2      0.8595
br_sigma1       0.1222
br_sigma2       0.0748
p1_amplitude    0.5845
p1_center       0.3514
p1_fwhm         0.2878
p1_sigma        0.1222
p2_amplitude    0.2016
p2_center       0.8595
p2_fwhm         0.1761
p2_sigma        0.0748
```

Customize column width, precision and numeric format:

```python
>>> params.pretty_print(colwidth=10, precision=1, fmt='e')
Name               Value        Min        Max     Stderr       Vary       Expr
br_amplitude     7.8e-01    0.0e+00        inf    5.3e-02       True       None
br_center1       3.5e-01    0.0e+00        inf    4.9e-03      False  p1_center
br_center2       8.6e-01    0.0e+00        inf    1.0e-02      False  p2_center
br_sigma1        1.2e-01    0.0e+00        inf    4.7e-03      False   p1_sigma
br_sigma2        7.5e-02    0.0e+00        inf    8.5e-03      False   p2_sigma
p1_amplitude     5.8e-01    1.0e-02        inf    2.0e-02       True       None
p1_center        3.5e-01   -1.0e-01    6.0e-01    4.9e-03       True       None
p1_fwhm          2.9e-01       -inf        inf    1.1e-02      False 2.3548200*p1_sigma
p1_sigma         1.2e-01    1.0e-02    2.0e-01    4.7e-03       True       None
p2_amplitude     2.0e-01    1.0e-02        inf    2.3e-02       True       None
p2_center        8.6e-01    5.0e-01    1.1e+00    1.0e-02       True       None
p2_fwhm          1.8e-01       -inf        inf    2.0e-02      False 2.3548200*p2_sigma
p2_sigma         7.5e-02    1.0e-02    2.0e-01    8.5e-03       True       None
```

**Comment by tritemio** [comment]
Forgot to mention that I rebased it.

**Pull request merged**
