### PR TITLE
lineshapes: clean-up and improve tests coverage

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR contains changes to `lineshapes.py` and its test-suite:
- remove unused `assert_results_close` function
- remove unused `_<func>` functions that shadow the ones in `scipy`
- separate tests for lineshapes and built-in models into two different files
- explicit checking/testing of `form` argument
- minor corrections in docstrings and fix a 'wrong continued indentation'
- use `max(tiny, [decay|expon|sigma])`, where `tiny = np.finfo(np.float64).eps` in `exponential`, `pearson7`, and `logistic` to make sure the functions always give a finite result and there is no `ZeroDivisionError`. I think it's correct like this, but please check.

I've been working on some more explicit for the individual lineshape function, but that's not completely finished yet. I'd prefer to see the response to this PR first and will finish up the test-suite later.

###### Type of Changes

- [x] Refactoring / maintenance
- [x] Test-suite

###### Tested on
Python: 3.8.2 (default, Feb 27 2020, 15:26:21)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 1.0.0+37.g75a4ce8, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2

###### Verification 
Have you
- [x] included docstrings that follow PEP 257?
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] added or updated existing tests to cover the changes?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Nice!  This all looks good to me.  It seems that some of the tests that were in 
`test_finite_output_lineshape` didn't get moved to `test_lineshapes`.  I'm not sure this is important (the coverage definitely went up!) but should some of those checks be kept?  I don't have much preference - it would mostly be to prevent future breakage which seems very unlikely....

**Comment by reneeotten** [comment]
> @reneeotten Nice! This all looks good to me. It seems that some of the tests that were in
> `test_finite_output_lineshape` didn't get moved to `test_lineshapes`. I'm not sure this is important (the coverage definitely went up!) but should some of those checks be kept? I don't have much preference - it would mostly be to prevent future breakage which seems very unlikely....

Removing tests was likely not intended - I'll check and report back.

**Comment by reneeotten** [comment]
@newville it might look like that not all the tests were copied over, but in fact that's not true. You'll notice in `test_lineshapes.py`:

```
@pytest.mark.parametrize("lineshape", lmfit.lineshapes.functions)
def test_no_ZeroDivisionError_and_finite_output(lineshape):
```

so this test will run for all lineshapes that are exposed from `lmfit.lineshapes.functions`. In addition, I made use of `inspect.signature` in the new test, so there is no reason anymore to explicitly specify for every lineshape what the `func_args` should be.

To the best of my knowledge all tests (and a bit more) are present.

**Comment by newville** [comment]
@reneeotten OK, great!  I'll merge this..

**Pull request merged**
