### PR TITLE
drop support for Python 3.6

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
Python 3.6 reached its EOL status a while go. This PR "officially" removes support for it and stops testing in the CI workflow.  

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.10.5 (main, Jun  7 2022, 09:02:20) [Clang 11.0.3 (clang-1103.0.32.62)]

lmfit: 1.0.3.post36+ga9c6b06, scipy: 1.8.1, numpy: 1.22.4, asteval: 0.9.27, uncertainties: 3.1.6

###### Verification 
Have you
- [x] verified that existing tests pass locally?
- [x] verified that the documentation builds locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten Thanks - I'm +1 on dropping Py3.6 support.   I'd be happy to merge, but I don't fully understand the test failures, especially for "calc_covar" -- they look separate from the changes here.  I think I don't have the capacity to look into this soon, but if you have an opinion or idea, I'll completely defer to you.   Anyway: merging this is fine with me!

**Comment by reneeotten** [comment]
@newville I fixed the failures already in `master` but pushed them directly instead of opening a PR. It turns out that in some instances the example we use in `test_itercb.py` converges before our stop criterion (used to be 23 iterations) was reached. I changed this already to `17` in `master` but fixed that after submitting this PR. I'll rebase and push again - it should then pass without trouble.

**Comment by newville** [comment]
@reneeotten Ah, OK, great.  Yeah, I guess some of these tests that rely on exact results might need adjusting over time.  I would probably err on the side of tolerance, asserting something like "there need to be more than 10 iterations" (and maybe "fewer than 1000" if we're asserting on that end too).

**Comment by reneeotten** [comment]
> @reneeotten Ah, OK, great. Yeah, I guess some of these tests that rely on exact results might need adjusting over time. I would probably err on the side of tolerance, asserting something like "there need to be more than 10 iterations" (and maybe "fewer than 1000" if we're asserting on that end too).

@newville True, but in this case we were testing to make sure that the fit stops when you specify an `iter_cb` call, and if we return something there at a specific iteration then that should be the *exact* value of `.nfev`. Except of course when the fit converges before we reach that criterion as was the case here.

**Comment by newville** [comment]
@reneeotten Ah, OK.  So is it more like "it should take 20 + a few" function calls?

**Comment by reneeotten** [comment]
no, the fit should stop *exactly* at the correct value for "nfev" since we only then return something with the "iter_cb" function (you can check the code in test_itercb.py). 

The issue here was that the fit converged before the number of specified iterations was reached. Therefore the value for ".nfev" was smaller and the ".success" was still True. Hence the failures... anyway, doesn't matter - it's fixed now.

**Pull request merged**
