### PR TITLE
fix: json encode should preserve numbers type (int/float)

### PR DESCRIPTION
**Pull request by jedzill4**
#### Description

When the `jsonutils.encode4js` routine (called by `model.save_model`)  encode integer model attributes, as floats, it breaks things when the `ResultModel` is loaded again. In my case breaks `ResultModel.eval_uncertainty` when try to instance  [`fjac = np.zeros((nvarys, ndata))`](https://github.com/lmfit/lmfit-py/blob/20e09ecd347fa0b4716469f5dc397cc9b9544a9e/lmfit/model.py#L1482) 'cause `nvarys` is a `float` when should be an `int`.

###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

```
Python: 3.7.9 (default, Oct 30 2020, 14:07:29) 
[GCC 10.2.0]

lmfit: 1.0.1+137.g0ac0c7a, scipy: 1.6.0, numpy: 1.19.5, asteval: 0.9.21, uncertainties: 3.1.5
```

###### Verification 
Have you
- [x] verified that existing tests pass locally?
  It has 2 fails:
 ```
FAILED tests/test_jsonutils.py::test_encode_decode[10-float] - AssertionError: assert False
FAILED tests/test_saveload.py::test_save_load_modelresult[False] - assert 13400 < 13374
  ```
  But both fails are also present in HEAD (20e09ec)

- [x] squashed/minimized your commits and written descriptive commit messages?

### CODE REVIEW

**Comment by Tillsten** [comment]
Good catch. It likley did work with older numpy version, but they depracted accepting floats for shapes and indicies a long time ago. So do the tests pass after the patch?

**Comment by reneeotten** [comment]
@jedzill4 that change looks fine. However you will need to update the tests that now fail in our CI (e.g., in `test_jsonutils.py`) since you changed the return type. Also, I am pretty sure none of the failures are present in the `master` branch as there all tests pass.

**Comment by Tillsten** [comment]
@reneeotten Already pushed that change to the test

**Comment by Tillsten** [comment]
Since the open source commitment of TravisCI is now less secure, anyone of us has experience with changing our CI provider?

**Comment by newville** [comment]
@jedzill4 Yeah, thanks for catching this!  It is sort of confusing about test failures, but I think @Tillsten is right that it must be due to numpy versions and accepting floats as array sizes.   Changing the tests to work with only integers when making arrays seems like the right thing to do.

For @Tillsten's other question about Travis-CI, I think a good approach would be to add azure pipelines.  That said, I don't know very much about setting that up.  But, if that happens then once both are working we could then deprecate using Travis.    Sorry, I have not had a lot of bandwidth for this project in recent months and I'm not sure I'll much time for this going forward, but if someone out there has experience with azure, adding that would be much appreciated!

**Comment by reneeotten** [comment]
> For @Tillsten's other question about Travis-CI, I think a good approach would be to add azure pipelines. That said, I don't know very much about setting that up. But, if that happens then once both are working we could then deprecate using Travis. Sorry, I have not had a lot of bandwidth for this project in recent months and I'm not sure I'll much time for this going forward, but if someone out there has experience with azure, adding that would be much appreciated!

Alternatively, we could probably used GitHub Actions - but admittedly, I don't have much experience with either of them... I would prefer to kind-of replicate what we do know.
1. run pre-commit
2. do the tests with the different supported Python version and minimum/current versions of dependencies
3. test building the documentation

**Comment by reneeotten** [comment]
okay, one more change to the tests as it also appears that the length of the resulting save file has changed a little bit. Likely these values were a little strict already in the past and the actual value  really does not matter that much - we just want to make sure that we have written a correct output file.

Hopefully this all passes now and then I think it should be good to go!

**Pull request merged**
