### PR TITLE
ENH: a couple of benchmarks for suite

### PR DESCRIPTION
**Pull request by andyfaff**
Adds differential_evolution and emcee to asv test_suite.

### CODE REVIEW

**Comment by andyfaff** [comment]
Note: tests might fail because there is a benchmark in there that uses the `seed` kwd for `Minimizer.emcee`, which is not present in master. #306 adds this keyword.

**Comment by andyfaff** [comment]
It might be a good idea to merge #306 into master, then rebase this branch onto master.

**Comment by newville** [comment]
@andyfaff  Yeah, I don't disagree.  A couple of points: 

1.  I expect #303 to be merged, as min/max as inf instead of properties, and the use of `ifs` instead of function calls to `min()` and `max()` sort of has to be better -- maybe not much, but it really can't be worse performance.

2. I definitely won't have time to work on this over the next couple days, or the rest of this evening (for me ;) ). 

So, I suggest that we (that is, you) merge all of #303, #306, and #307 into master now, and work from that for the next release, including adding the benchmarking web pages.   I'm not saying these PRs are perfect, or that we can't change these features, layouts, and so on.  But, I think we're going to merge them all at some point, and we're mostly on the same page.  I also think there is little chance of problems that we can't fix.

**Comment by andyfaff** [comment]
I can't merge on the lmfit-py master, I don't have commit rights :-). I can
only work on my fork.

On 22 February 2016 at 14:15, Matt Newville <notifications@github.com>
wrote:

> @andyfaff <https://github.com/andyfaff> Yeah, I don't disagree. A couple
> of points:
>
>    1.
>
>    I expect #303 <https://github.com/lmfit/lmfit-py/pull/303> to be
>    merged, as min/max as inf instead of properties, and the use of ifs
>    instead of function calls to min() and max() sort of has to be better
>    -- maybe not much, but it really can't be worse performance.
>    2.
>
>    I definitely won't have time to work on this over the next couple
>    days, or the rest of this evening (for me ;) ).
>
> So, I suggest that we (that is, you) merge all of #303
> <https://github.com/lmfit/lmfit-py/pull/303>, #306
> <https://github.com/lmfit/lmfit-py/pull/306>, and #307
> <https://github.com/lmfit/lmfit-py/pull/307> into master now, and work
> from that for the next release, including adding the benchmarking web
> pages. I'm not saying these PRs are perfect, or that we can't change these
> features, layouts, and so on. But, I think we're going to merge them all at
> some point, and we're mostly on the same page. I also think there is little
> chance of problems that we can't fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmfit/lmfit-py/pull/307#issuecomment-186980882>.
>



-- 
_____________________________________
Dr. Andrew Nelson


_____________________________________

**Comment by newville** [comment]
@andyfaff  I added you to developers.  I'll merge #303 and #306, and leave this one for you (maybe change names of both classes -- too similar).

**Pull request merged**
