### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by reneeotten**
This PR contains only updates to docstrings and style-changes to the code to follow PEP8 more closely. In other words, some housekeeping before moving on.

### CODE REVIEW

**Comment by reneeotten** [comment]
well... Travis should certainly not fail here... it seems to be a problem on their side, not in the code:

```oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"```

**Comment by newville** [comment]
@reneeotten Thanks!  From a quick look, this all looks good to me.  

My only concern is about the replacing of `if len(thing) > 0` with `if thing`.  To me, `len(thing) > 0` is more specific and implies `thing` is meant to be a string or sequence, and so seems more explicit.  That's not a strong preference -- feel free to outvote me.

TheTravis failure for one of the test seems bogus to me.

**Comment by newville** [comment]
@reneeotten OK, great (and Travis is fixed!).  Let me know what you think about `if len(thing) > 0` versus `if thing`, and when you think this is ready for merging.

**Comment by reneeotten** [comment]
@newville I think it's ready to for merging.  PEP8 says ```For sequences, (strings, lists, tuples), use the fact that empty sequences are false.``` and I am personally in favor of using that; the only instance where I didn't change anything is where it involves numpy arrays - that's typically more tricky. 

But, I have no strong preference either and if you prefer to keep it as-as, just drop that commit or tell me to do so and then you can merge it.

**Comment by newville** [comment]
@reneeotten  I'm not really committed to following PEP-8 zealously.  It's good for spacings, etc, but the 80-char line limit does more harm than good.   For me, the biggest appeal for me is that if everyone follows it, all code is generally easier to read.

After thinking about this more, I'm going to disagree with the length recommendation.  That really is a code change -- any True-ish value will satisfy `if thing` and any False-ish value will silently, happily fail.  But only non-empty sequences will pass `if len(thing) > 0`, and any non-sequences (say, `None`) will raise an exception.   PEP-8 is wrong on this.

**Comment by reneeotten** [comment]
@newville okay - I dropped that commit.

**Comment by newville** [comment]
@reneeotten Great -- thanks so much!

**Pull request merged**
