### PR TITLE
Add result call kws

### PR DESCRIPTION
**Pull request by newville**
This adds a `call_kws` attribute to `MinimizerResult` that contains the keyword arguments sent to the underlying solver. 

There are also a few tweaks to tests.

#### Description

This is basically to inform the user what keywords were actually sent to the solver.

Inspired by https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lmfit-py/W5nFfIsfSow/DHQHqExqAgAJ

###### Type of Changes

- [ ] Bug fix
- [*] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on

Python: 3.7.7 (default, Mar 23 2020, 17:31:31)
[Clang 4.0.1 (tags/RELEASE_401/final)]

lmfit: 1.0.0+79.g382ce5f, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2

###### Verification 
Have you

- [ ] included docstrings that follow PEP 257?

- [ ] referenced existing Issue and/or provided relevant link to mailing list?

- [*] verified that existing tests pass locally?

- [*] verified that the documentation builds locally?

- [ ] squashed/minimized your commits and written descriptive commit messages?

- [ ] added or updated existing tests to cover the changes?
- [*] updated the documentation?
- [ ] added an example?

### CODE REVIEW

**Comment by reneeotten** [comment]
@newville this looks like a useful addition which makes it easier to see for the user which arguments are passed down to the solver. I'm all in favor; eventually, we can/should probably do some checking of this attribute in our test to assert that the options we want to pass are actually happening. But that can be done separately at a later time.

**Comment by newville** [comment]
@reneeotten Yes, I agree.  It sort of feels like adding tests for this would be overkill at this point.  It might be better to decide we actually like having this before testing what its format is.

I'll merge this.   Any objections to this being 1.0.1?

**Comment by reneeotten** [comment]
> I'll merge this. Any objections to this being 1.0.1?

@newville not really, but I do have a few small (style) updates to docstrings and tests that are almost ready. If you want I can write a "whats-new" section and put those things up as a PR tomorrow, with that I think we're ready for a release.

**Comment by newville** [comment]
@reneeotten Sure, that would be great!

**Pull request merged**
