### PR TITLE
Remove long() and use builtins.int() for py2/3 comp

### PR DESCRIPTION
**Pull request by tritemio**
Addresses #319

### CODE REVIEW

**Comment by newville** [comment]
@tritemio    Hmm, looks like `from builtins import int` is **not** valid Python2....  But if you're removing the `__long__()` method anyway, do we need this import?

**Comment by tritemio** [comment]
It is valid python 2. It is our travis environment that does not install the package `future` which provides `builtins`.

I left the import because we call `int()` and with the `builtins` import we would use long integers on both python 2 and 3. Just consistency.

**Comment by tritemio** [comment]
Ok, the problem is that `future` currently **is not** a dependency for lmfit. My mistake, I though it was.

Either with add `future` as a dependency (which is a very nice way to achieve python2/3 code) or we ignore the inconsistency (of having different ints in python 2 and 3) and remove the `from builtins import int`

**Comment by newville** [comment]
@tritemio Great, thanks!

**Pull request merged**
