### PR TITLE
Fix test_hints_for_peakmodels from test_models.py

### PR DESCRIPTION
**Pull request by eendebakpt**
###### Type of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Refactoring / maintenance
- [ ] Documentation / examples

The `test_hints_for_peakmodels` from `test_model.py` is failing on my system. I suspect due to changes in the accuracy of np.sin and np.cos in the upcoming numpy 1.25 release. See https://github.com/numpy/numpy/pull/23399. The test  `test_hints_for_peakmodels` fails at the comparison
```
   self.assertTrue(param_values['m1_intercept'] < -0.0)
```
due to numerical rounding errors. 

In this PR we increase the threshold of the comparison. Since the test itself is not about the values (according to the docstring about checking asteval), this seems safe.

###### Tested on

Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

lmfit: 1.0.2.post286+g980a5d1, scipy: 1.10.1, numpy: 1.25.0rc1+97.g4e69d516c, asteval: 0.9.30, uncertainties: 3.1.7

###### Verification 
Have you

- [x] included docstrings that follow PEP 257? Only tests have changed

- [x] referenced existing Issue and/or provided relevant link to mailing list?

- [x] verified that existing tests pass locally?

- [x] squashed/minimized your commits and written descriptive commit messages?

- [x] added or updated existing tests to cover the changes?
- [x] updated the documentation and/or added an entry to the release notes (doc/whatsnew.rst)? Not required, internal change

### CODE REVIEW

**Comment by newville** [comment]
@eendebakpt Thanks -- looking at that test, and with the view that tests are really "promises for how the code should behave", I have to say that I do not like that test.  I would be in favor of changing those asserts to

```
        self.assertTrue(param_values['m1_intercept'] < 1000)
        self.assertTrue(param_values['m2_amplitude'] > 0)
```

I think for the behavior that we intend to test there, we just want to test "the parameters do not have absurd initial values".

I suspect that we sort of have a lot of tests that are testing values too much higher accuracy than we intend to test.

**Comment by reneeotten** [comment]
@newville @eendebakpt our test seems to work just fine with NumPy 1.25.0 on all variations we test (macOS, Python 3.11; Linux, Python 3.7-3.11; Windows, Python 3.10) and have done so for at least the last 6 years (5a085bc642bdb1faf694319b329788a2f18e7c94). 

So I am not sure why this fails for you now it must be because of a certain architecture and you don't show how "far" your values are off. I am not necessarily against changing the values (probably not as dramatically as @newville suggests though) but more importantly we should probably move away from using `self.asserEqual` (from `unittest`) and use `assert_allclose` instead as we do elsewhere; that would probably resolve the failure as well.

**Comment by eendebakpt** [comment]
@reneeotten The value on my system for `param_values['m1_intercept']` is `0.` (which fails since `0 < -0.` evaluates to `False`). 

I am not running the final numpy 1.25.0, that might explain the differences (in particular I do not have PR https://github.com/numpy/numpy/pull/23925 which appears to revert some of the sin/cos changes).

I updated the PR with your suggestion to use `assert_allclose`

**Comment by reneeotten** [comment]
> I am not running the final numpy 1.25.0, that might explain the differences (in particular I do not have PR https://github.com/numpy/numpy/pull/23925 which appears to revert some of the sin/cos changes).

well, in your PR your suggesting/claiming that the issue is caused by NumPy v1.25 so them it would be good that you're actually running that. Did you confirm that you still experience an issue when you have the latest released versions of all dependencies. If not, then there is no reason to change anything. 

> I updated the PR with your suggestion to use `assert_allclose`

The question here is: did that solve the test failure on your specific installation?

**Comment by newville** [comment]
@eendebakpt @reneeotten Hmm the new failure is at https://github.com/lmfit/lmfit-py/blob/master/tests/test_shgo.py
where the failure is on the expected results of running `scipy.optimize.shgo`.  
```
    result_scipy = scipy.optimize.shgo(eggholder, bounds, n=30,
                                       sampling_method='sobol')

    # in SciPy v1.7.0: "sobol was fixed and is now using scipy.stats.qmc.Sobol"
    # FIXME: clean this up after we require SciPy >= 1.7.0
    if int(scipy_version.split('.')[1]) < 7:
        assert len(result_scipy.xl) == 13
    else:
        assert len(result_scipy.xl) == 6
```

Why on earth are we testing results of running `scipy.optimize.shgo`?   That is literally not our code.

For the test here, I'm OK with saying that the intercept should be around 0.  But, the point of this test is actually not the precise values of
```
         assert_almost_equal(param_values['m1_intercept'], 0.)
         self.assertEqual(param_values['m2_amplitude'], 1)
```

The test is literally described as "test that height/fwhm do not cause asteval errors."   Neither of those assertions has anything to do with that. 

We have 3 very clear examples of over-testing and overstating the precision of the tests we run.  

I think we should merge this and then clean up the tests.

**Comment by newville** [comment]
@eendebakpt If you pull from the lmfit master branch into your PR branch and push that back here, then all the tests should pass, and we will merge.

**Comment by newville** [comment]
@eendebakpt If you pull from the lmfit master branch into your PR branch and push that back here, then all the tests should pass, and we will merge.

**Comment by reneeotten** [comment]
please see my comments above; it looks like there was no need to change anything in these tests as the CI currently passes. So I am not sure why we would...

@newville the reason we were testing to make sure that `SciPy` and `lmfit` give the same/similar results is to make sure that the way we wrap the function and such is working as intended. So yes, if SciPy has changed something in newer versions that might need some minor adjustment, but it's a perfectly fine thing to do ;) As usual for most of the tests that I've added over the years, if something breaks I'll get to fixing it - but sure, removing tests because they don't pass out-of-the-box anymore is an option as well.

**Comment by newville** [comment]
@reneeotten the test results for this PR still show several failing tests.   I believe these failures are not from the PR itself, but from changes in upstream packages (numpy *and* scipy).  The master branch now has fixed these, so this PR could be merged in.  

I'm willing to wait (but not indefinitely) for @eendebakpt to merge in the recent changes on master back to this PR to prove that the change here does not cause problems -- it will not.  I am also willing to just merge as is, and take any responsibility for fixing any problems that arise.  That is, the fix from @eendebakpt is clear and correct and we should definitely merge it.

**Comment by reneeotten** [comment]
> @reneeotten the test results for this PR still show several failing tests. I believe these failures are not from the PR itself, but from changes in upstream packages (numpy _and_ scipy). The master branch now has fixed these, so this PR could be merged in.
> 
> I'm willing to wait (but not indefinitely) for @eendebakpt to merge in the recent changes on master back to this PR to prove that the change here does not cause problems -- it will not. I am also willing to just merge as is, and take any responsibility for fixing any problems that arise. That is, the fix from @eendebakpt is clear and correct and we should definitely merge it.

sure, there are test failures with this PR that are due to NumPy / SciPy. I understand that, but with the commits you did today these failures have been resolved and the current `master` branch passes the CI.

So my point is that none of the actual changes in this PR are necessary and that these tests that you added 6 years ago in 5a085bc642bdb1faf694319b329788a2f18e7c94 are still perfectly fine. So this PR can just be closed IMHO.

**Comment by eendebakpt** [comment]
@eendebakpt @reneeotten I rebased to latest master.

Let's not spend too much time on this. I am fine with either merging this, or closing.

**Comment by newville** [comment]
@eendebakpt Thanks - I'll merge this.

**Pull request merged**
