### PR TITLE
changes to the Parameter class and increase coverage

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
While working on improving the coverage of the test-suite I came across some minor inconsistencies in the ```Parameter.__repr__``` function. 

Consider the following examples:
```
>>>import lmfit
>>>lmfit.Parameter(name=‘test’, value=10)
<Parameter 'test', 10, bounds=[-inf:inf]>

>>>lmfit.Parameter(name='test', value=10, vary=False)
<Parameter 'test', value=10 (fixed), bounds=[-inf:inf]>

>>>lmfit.Parameter()
<Parameter -inf, bounds=[-inf:inf]>
```
Currently, only when a Parameter is fixed or has a ```stderr``` attribute it will show “value”; otherwise is’t just the number.  Additionally, when no ```name``` is specified the output also looks different. 

I suggest to change the behavior so that “value” is always printed ahead of the parameter value, and that when no “name” is specified we show it as ''. So when this PR gets merged the first and last situation would give instead as output:
```
>>>lmfit.Parameter(name=‘test’, value=10)
<Parameter 'test', value=10, bounds=[-inf:inf]>

>>>lmfit.Parameter()
<Parameter '', value=-inf, bounds=[-inf:inf]>
```
Once we have switched to Python 3 only we should probably convert the using f-strings, which likely means the ```__repr__``` function can get a bit shorter.

###### Type of Changes

- [ ] Bug fix
- [ ] New feature
- [X] Refactoring / maintenance
- [ ] Documentation / examples

###### Tested on
Python: 3.7.5 (default, Oct 16 2019, 10:21:13)
[Clang 10.0.1 (clang-1001.0.46.4)]

lmfit: 0.9.14+23.g85b6341, scipy: 1.3.1, numpy: 1.17.2, asteval: 0.9.15, uncertainties: 3.1.2, six: 1.12.0

###### Verification 
Have you
- [x] verified that existing tests pass locally?
- [x] squashed/minimized your commits and written descriptive commit messages?
- [ ] added or updated existing tests to cover the changes? Currently working on the test-suite, there will be tests included there

### CODE REVIEW

**Comment by reneeotten** [comment]
> Maybe we just should disallow parameters without a name? Or is there a usecase I dont see?

Good point @Tillsten. I would agree with requiring a name for Parameter as I also don't see a use-case for "unnamed " Parameters ,and am happy to change this. @newville do you remember why Parameter names are optional and do you see any issues with changing that?

**Comment by reneeotten** [comment]
@newville any insights and/or comments?

**Comment by newville** [comment]
@reneeotten This looks fine to me.  I agree that `__repr__` should always show name and value. 

I agree with @Tillsten that a Parameter without a name is probably a bad idea.  I wonder (but haven't checked myself) what would fail if we just made `name` a positional argument.  I don't know if that is something that should be tackled here (maybe?), but it's definitely worth considering for version 1.0.   

Does an unnamed Parameter ever make sense?

**Comment by reneeotten** [comment]
> Does an unnamed Parameter ever make sense?

I don't think it makes ever sense to have an unnamed Parameter... so let's try to change that here. I'll make ```name``` a required argument and see if there is any fallout. I'll follow up here with either an update to the PR or a comment if there are unexpected side effects.

**Comment by newville** [comment]
@reneeotten should we merge this and then consider whether to make `name` a required argument?

**Comment by reneeotten** [comment]
> @reneeotten should we merge this and then consider whether to make `name` a required argument?

@newville sorry for the delay... but let's hold off a little bit longer. I am almost finished with it: made a few more small changes and completed the test-suite for the Parameter class as well. I should be able to push the updated PR by the end of the week or latest in the weekend.

**Comment by newville** [comment]
@reneeotten  OK, great!

**Comment by reneeotten** [comment]
In addition to the things discussed earlier (i.e., make ```__repr__``` consistent and require a Parameter ```name```) the following changes are made as well:

- complete test coverage for the Parameter class (I'll continue on this and likely incorporate/clean-up some tests that are currently in other files)
- update the magic methods; make Python 3 ready while retaining backwards compatibility

Two things can be deprecated I think or perhaps just removed directly, depending on what others think. I have added a ```FutureWarning``` to both parts of the code - it's never used in the lmfit codebase and -to me- it doesn't seem all that useful for the end-user:

1. the function ```isParameter``` to test if something is an instance of the Parameter class
2. in ```_getval()``` it appears one could supply an ```uncertanties``` object instead of an integer/float to the Parameter ```value```.

**Comment by reneeotten** [comment]
@newville  @Tillsten any additional comments on this PR? Please let me know as well what you think about deprecating versus immediately removing the few things I listed above. Thanks!

**Comment by Tillsten** [comment]
Just one comment: For the examples I would prefer `Parameter('myName')` instead of the more explicit form `Parameter(name='myName')` used now.

Btw: I am always fine with breaking things, since this project is a free offer where it is also always possible to go back to an old version.

**Comment by reneeotten** [comment]
> Just one comment: For the examples I would prefer `Parameter('myName')` instead of the more explicit form `Parameter(name='myName')` used now.
> 
> Btw: I am always fine with breaking things, since this project is a free offer where it is also always possible to go back to an old version.

Thanks for the comments @Tillsten. Just to make sure, you can still do ```Parameter('myName')``` in your own code, that has not changed. In the few instances where I needed to add a ```name``` for a Parameter in this PR (i.e., in an example and ```model.py```), I certainly prefer the explicit form as that is completely clear without looking at the initialization of the class.

**Comment by Tillsten** [comment]
From my point of view, using the explicit form wrong leads to assumption that name is not the first argument and may be even optional, hence I prefer the form without the keyword.

**Comment by reneeotten** [comment]
> From my point of view, using the explicit form wrong leads to assumption that name is not the first argument and may be even optional, hence I prefer the form without the keyword.

okay, I changed it as suggested in the example file. In ```model.py``` I would prefer to keep it as ```_par = Parameter(name='')```; how is that for a compromise ;)

**Comment by reneeotten** [comment]
@newville do you have any preference for removing or first deprecating or immediately removing the ```isParameter``` function and allowing for an ```uncertainties.core.Variable``` in the ```_getval``` function? Or, do you think these are actually useful and do you want to keep them as-is. Besides, that I think this should be (almost) ready-to-go.

**Comment by newville** [comment]
@reneeotten I think that check on `uncertainties.core.Variable` in `Parameters._getval` can be dropped, even without deprecation.  I think it was never advertised and it sort of wart.   

I have no general preference between `Parameter('x', value=1)` and `Parameter(name='x', value=1)`. 

Happy to merge when you say it is ready!  Thanks!

**Comment by reneeotten** [comment]
@newville okay, let's keep the deprecation/FutureWarning in there for now - it doesn't hurt. We can remove both things at the following release - just in case someone relies on these two things right now. I consider this done; so feel free to merge or I'll do it myself later in the week.

**Pull request merged**
