### PR TITLE
Fixes/updates to examples

### PR DESCRIPTION
**Pull request by reneeotten**
This PR is related to examples and documentation and includes the following changes:

1. fixes so that all examples run again with Python 2/3 and newer versions of lmfit (see #431 and #437, even though I doesn't address testing...).
2. static-code analysis and style changes to all examples
3. updates to the documentation to reflect output/figures obtained with current versions of lmfit and matplotlib
4. updates to Jupyter notebooks and addition of a notebook describing the `brute` method
5. suggested change to naming convention of examples used in the documentation to: doc_\<chapter>\_\<description>\.py

I do realize that there are a lot of coding-style-related changes, but I do think having "proper" (I know that's a debatable term) and consistent code does help for readability, especially for code that appears in the documentation. But as always it's up for discussion here and a final decision by @newville 

There are two examples related to `emcee` don't work properly  (`lmfit_emcee_model_selection.ipynb` and `lmfit_and_emcee.py`). The latter one I changed to get it to run, but probably did something wrong (I am also not sure that we still need this one, as there is a Jupyter notebook and description in the documentation with very similar scope)... the Jupyter notebook does not reproduce the same results and there is something weird going on that I cannot seem to figure out... Perhaps @andyfaff would be willing to take a look at these to examples?

### CODE REVIEW

**Comment by newville** [comment]
@reneeotten  That looks awesome!  I don't know why Travis thinks some checks haven't completed, but I'd be strongly in favor of merging though I'd like to give @andyfaff and others a chance to look it over, especially with regard to the Jupyter notebook. 

Are Jupyter notebooks too fragile / unstable (as text files, not in how that is interpreted) to include? 
Other projects must have figured that out pretty well.

**Comment by reneeotten** [comment]
@newville Travis seems indeed to be confused - if you click on "Details" you will see that all checks completed just fine.... but waiting a little for other to pitch in is always a good idea before merging! 

Jupyter notebooks are perfectly fine to include, especially as unexecuted code as Andrew mentioned earlier - that's what I did for "my" ```brute``` example. I would be in favor of converting all the non-documentation related example files (i.e., not starting with ```doc_```) to Jupyter notebooks, probably consolidating them by topic. However that only make sense if there is some 'story-telling' happening as well in these notebooks, otherwise you can just leave them as plain, good-old Python code. Unfortunately, that will require a time investment on top of this PR that I am currently not able (or better: willing) to make.

**Comment by newville** [comment]
@reneeotten Thanks, I agree with all of that.   I'll plan on merging this in a few days unless I hear objections or concerns.

**Comment by newville** [comment]
@reneeotten  OK, I'm merging this then #442.  Awesome work!

**Pull request merged**
