### PR TITLE
update to versioneer 0.18

### PR DESCRIPTION
**Pull request by newville**
this updates versioneer to 0.18, the latest version.  This seems to avoid some problems with the latest setuptools on oldish python 2.7.

### CODE REVIEW

**Comment by reneeotten** [comment]
As I noticed myself when updating to a newer versioneer version on another project, it adds the following code 
```
from ._version import get_versions
__version__ = get_versions()['version']
del get_versions
```
to your `__init__.py` even if it's already there. So you have now duplicated that code... besides that it should be all good.

**Comment by newville** [comment]
@reneeotten Thanks -- good catch!  I updated the PR.

**Comment by newville** [comment]
@reneeotten  @Tillsten @andyfaff  Any objections to merging this?

**Comment by andyfaff** [comment]
No

**Comment by reneeotten** [comment]
no objections at all

**Comment by Tillsten** [comment]
I don't even have an idea what versioneer does ... :)

**Comment by newville** [comment]
@Tillsten versioneer uses the git commit hash to construct a unique version string like '0.9.5+58.ga7f2ea', which is very useful when developing/debugging.

**Pull request merged**
